### ISSUE TITLE
Fix CPU count autodetection

### ISSUE THREAD

**Issue by hanwen** [google/bazel#101]
on OSX, we fall back to 
  https://github.com/google/bazel/blob/master/src/main/java/com/google/devtools/build/lib/actions/LocalHostCapacity.java#L129

which hardcodes the CPU count at 2. Instead, use JNI to wrap sysconf(), see also:

 http://stackoverflow.com/questions/4586405/get-number-of-cpus-in-linux-using-c

**Comment by hanwen** [comment]
also, on OSX, 

int count;
size_t count_len = sizeof(count);
sysctlbyname("hw.logicalcpu", &count, &count_len, NULL, 0);
fprintf(stderr,"you have %i cpu cores", count);

(source: http://stackoverflow.com/questions/1715580/how-to-discover-number-of-cores-on-mac-os-x)

**Comment by hanwen** [comment]
On Linux,

   /sys/devices/system/cpu/cpu11/topology/core_id
  =>
  5

we can use this to detect both physical and logical cores.

**Comment by srib** [comment]
Hanwen,

I have a solution to this. I only have access to a Linux machine and I cannot test it on Mac. 

Is there a way someone can help me improve this? If it works, let me know and I can send a pull request.

**Comment by hanwen** [comment]
What is your solution? Just to be clear, we already detect the CPU count on Linux by parsing  /proc/cpuinfo, and it is the mac part that needs more attention. 

Can you send a gerrit code review? It'll be sufficiently complex that we might need a couple of rounds. For Gerrit:

Authentication is by https + gitcookie.

On gerrit go to Settings -> HTTP Password -> Obtain Password, then
authenticate and follow instructions to set up your ~/.gitcookies.

You also need to set up the gerrit hook for the Change-Id. Just try to
push and follow the instructions in the error message. E.g.:

**Comment by hanwen** [comment]
Alternatively, we have getRuntime().availableProcessors().

We currently take 0.6 of the total CPU count for HT CPUs. We could simply assume that all CPUs are HT today, and do 0.6 * getRuntime().availableProcessors(). How about that?

**Comment by hanwen** [comment]
On a related note: do we have something for the amount of memory as well? (the memory estimates are bogus, but I suspect things will blow up if we remove it completely.)
