### ISSUE TITLE
Can not get version of tool

### ISSUE THREAD

**Issue by emartynov** [google/bazel#102]
Maybe it is small thing but I think it is really important. 

I've updated repository and compiled `bazel`. But every time I try to get version I see next output:
```
Unrecognized option: --javabase=/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home
```

**Comment by damienmg** [comment]
It should work with all the other command. We are getting rid of what cause that bug.

**Comment by damienmg** [comment]
Daniel: can you do the follow-up of this bug when this stuff is actually removed?

**Comment by emartynov** [comment]
Thanks! I tried some other commands and they work

**Comment by hanwen** [comment]
Daniel, ping ?
