### ISSUE TITLE
"build ..." broken at 41c2f9ee09

### ISSUE THREAD

**Issue by claridge** [google/bazel#107]
Note that 41c2f9ee09 isn't sharp; that's just where I happened to try it out.

The below error occurs when running "build ..." in a client workspace. (/opt/makani/bazel is the path to my Bazel repo.)

$ bazel build ...
.....
ERROR: /opt/makani/bazel/output/classes/BUILD:87:1: //output/classes:srcs: invalid label 'autovalue/shaded/com/google/common/auto/common/MoreElements$1.class' in element 72 of attribute 'srcs' in 'filegroup' rule: invalid target name 'autovalue/shaded/com/google/common/auto/common/MoreElements$1.class': target names may not contain '$'.
ERROR: package contains errors: output/classes.
ERROR: error loading package 'output/classes': Package 'output/classes' contains errors.

**Comment by damienmg** [comment]
You are not supposed to build //...
See https://github.com/google/bazel/issues/103
