### ISSUE TITLE
$(location //external:foo) in genrule can't be handled properly

### ISSUE THREAD

**Issue by mzhaom** [google/bazel#111]
This is my [WORKSPACE](https://github.com/mzhaom/trunk/blob/master/WORKSPACE)

I wrote a genrule to call protoc to translate proto files:
```python
genrule(
  name = "test",
  srcs = [
    "bank.proto",
    "//external:protoc",
  ],
  cmd = "$(location //external:protoc) --cpp_out=$(GENDIR)/ $(location :bank.proto)",
  outs = [
    "bank.pb.h",
    "bank.pb.cc"
  ]
)
```

 but bazel doesn't like it:
ERROR: /usr/local/home/mzhao/g/trunk/examples/rpc/BUILD:7:9: in cmd attribute of genrule rule //examples/rpc:test: label '//external:protoc' in $(location) expression is not a declared prerequisite of this rule.
ERROR: /usr/local/home/mzhao/g/trunk/examples/rpc/BUILD:7:9: in cmd attribute of genrule rule //examples/rpc:test: $(location bazel-out/local_linux-fastbuild/bin/third_party/protobuf/protoc) not defined.
ERROR: Analysis of target '//examples/rpc:test' failed; build aborted.

**Comment by kchodorow** [comment]
When did you download/build bazel?  I pushed a fix for using location+//external yesterday: https://github.com/google/bazel/issues/90.

**Comment by mzhaom** [comment]
Thanks, this a duplicate of #90. I can verify it's fixed after pulling your change.
