### ISSUE TITLE
Transitive dependency errors for external dependencies don't print the offending target

### ISSUE THREAD

**Issue by ekuefler** [google/bazel#112]
When I make a reference to guava that in a package with a transitive dependency but no direct dependency, I get an error like this:

```
src/main/java/com/ekuefler/Processor.java:25: error: [strict] Using type com.google.common.base.Optional from an indirect dependency (TOOL_INFO: "jar/jar"). See command below **
  protected String getName(Optional<String> id) {
                                           ^
1 error
** Please add the following dependencies:
  jar/jar  to //src/main/java/com/ekuefler/presenters/template:template

** Please add the following dependencies:
  jar/jar  to //src/main/java/com/ekuefler/presenters/template:template
```

`jar/jar` doesn't help me find the missing dependency - I would want this to be `//external:guava`. It also doesn't seem like the message should be printed twice. I've defined the Guava dependency in my WORKSPACE like this:

```
maven_jar(
  name = "guava_maven",
  group_id = "com.google.guava",
  artifact_id = "guava",
  version = GUAVA_VERSION,
)
bind(
  name = "guava",
  actual = "@guava_maven//jar",
)
```

This isn't Guava specific, I get the name as `jar/jar` for every bound `maven_jar` dependency in my project.

**Comment by ekuefler** [comment]
Thanks for the super-quick fix. The error I see now looks like

```
** Please add the following dependencies:
  @guava_maven//jar  to //src/main/java/com/ekuefler/presenters/template:template
```

This is definitely an improvement, but it still means I have to go looking around the WORKSPACE file for the actual dependency I need to add (`//external:guava`). For local dependencies the target printed here can be copy-pasted directly into build files, which is quite helpful.

Does Bazel not have the information from `bind` available at this point in the analysis?

**Comment by kchodorow** [comment]
It does not.  We could add that info, but it will take a little longer and, honestly, I'd really like to get rid of the restriction that you can't use `@guava_maven//jar` in a BUILD file.

**Comment by ekuefler** [comment]
Sounds reasonable, definitely not a priority to fix.
