### ISSUE TITLE
Can't spawn builtin actions from a rule implementation

### ISSUE THREAD

**Issue by zrlk** [google/bazel#116]
I'd like to be able to use the builtin version of the C++ compilation action in a custom rule. Right now it seems like this is impossible and the only thing I'm able to do is cons up a string to pass to the shell, maybe referring to $(CC) and friends, and explicitly walking through ctx.targets.deps to figure out my includes and copts.

**Comment by laszlocsomor** [comment]
Supposing you're writing this in Skylark, does creating `native.cc_binary` help?

**Comment by hanwen** [comment]
Are you writing a "macro" (a function that expands at BUILD loading time and emits existing rules), or a native rule? If the latter, can you post a snippet or a more detailed explanation of what you are trying to do?

**Comment by zrlk** [comment]
The macro and rule we're using is https://github.com/google/kythe/blob/master/tools/build_rules/genproto.bzl ; for Java, this is based on genproto from Bazel's build_rules. Since we started the latter has grown a `java_compile_command`--why doesn't/shouldn't this use the builtin Java compile action?

**Comment by hanwen** [comment]
Java genproto is a bit of a special case. Since the output file names depend on the contents of the .proto file, it can't easily be fitted in as a normal Java compile (for normal Java compiles, you have to specify file names upfront.)

**Comment by hanwen** [comment]
I'm going to mark this as WAI.

If you want to depend on C++ artifacts, use a macro. If you want to interoperate with C++ code in rules, 
https://github.com/google/bazel/issues/146 is the right bug.
