### ISSUE TITLE
Unclear or impossible to return new `includes` from a custom rule

### ISSUE THREAD

**Issue by zrlk** [google/bazel#117]
(Running under a custom build of Bazel that grants genproto the same powers in C++ as it has in Java; see https://github.com/google/bazel/issues/114 ,) I'm not able to get a depending `cc_library` to respect the `includes` that are returned by a custom rule it depends upon. I've added `"includes"` to the custom rule's `providers` list.

**Comment by hanwen** [comment]
As detailed in #114 , you should be generating C++ sources, and bulding a cc_library from that. Does that work for you?

**Comment by zrlk** [comment]
I ended up writing a macro instead of a custom rule (see genproto_all in https://github.com/google/kythe/blob/master/tools/build_rules/genproto.bzl). With this approach I need to remember to depend on foo_proto_cc instead of foo_proto, but aside from that, things are working now.

**Comment by ulfjack** [comment]
Interoperability with native rules is a bigger topic than this bug.
