### ISSUE TITLE
Conflict between "List" and "list" types

### ISSUE THREAD

**Issue by claridge** [google/bazel#121]
If I create a macro and pass it a dict as one of its args, then any list values within that dict end up with type "List", which is incompatible with type "list". This leads to surprising messages like " unsupported operand type(s) for +: 'List' and 'list'".

Below is an illustration using a variation on the "Macro creating a native rule" example from the cookbook. Trying to "bazel build pkg:my_rule' will trigger the error I mentioned.

===== pkg/extension.bzl ====
def macro(name, dict_arg, visibility=None):
  dict_var = {"foo": []}
  d = dict_arg["foo"] + dict_var["foo"]

  # Creating a native genrule.
  native.genrule(
      name = name,
      outs = [name + '.txt'],
      cmd = 'echo hello > $@',
      visibility = visibility,
  )

===== pkg/BUILD ====
load("//pkg/extension", "macro")

macro(name = "myrule",
      dict_arg = {"foo": []})

**Comment by hanwen** [comment]
Laurent, can you have a look?

**Comment by hanwen** [comment]
Workaround:
  d = list(dict_arg["foo"]) + dict_var["foo"]
