### ISSUE TITLE
Support for Docker builds

### ISSUE THREAD

**Issue by schroederc** [google/bazel#122]
It's easy enough to write a Skylark rule for a Docker build, but it would nice to have official support.

**Comment by hanwen** [comment]
can you be more specific? What would the docker build rule do? Do you want to stage build products into a docker image? Write out a docker file script?

**Comment by schroederc** [comment]
What Kythe's campfire build system allows currently is for build artifacts to baked into Docker images and ensure one Docker image is built before another for proper "FROM" resolution.  Campfire also tries to make timestamps consistent between builds to ensure the Docker cache is utilized.  Finally, there's an extra campfire command to push the images to a particular registry.  I'm not sure how feasible that last one would be for Bazel.

**Comment by schroederc** [comment]
A Skylark rule is fairly straight-forward **except** that Docker does not play well with Bazel's symlink structure.  Docker doesn't like to add files that are outside of it's build context which is usually the entire source tree in a Bazel build context.

I don't have an easy workaround other than copying files into a new directory for Docker.

**Comment by sunyc** [comment]
+10 would love to see this too!

**Comment by damienmg** [comment]
FYI This has been scheduled as a team in Google did a support for Docker build.

**Comment by schroederc** [comment]
Is this now done with 5f25891bb17d19cb1208ddad1e88cc4bb4a56782?

**Comment by damienmg** [comment]
Yes sorry :)

**Comment by jylin** [comment]
This is a great feature! I'm wondering though if it would be possible to have some kind of support for interaction with Dockerfiles. Even if I would have to build the docker myself from the Dockerfile, and "docker save" to output a tar. If bazel could use that tar as a base image that would be useful. Then, I could create docker_build rules to add my jars. Is there some kind of support for doing something like that?

**Comment by damienmg** [comment]
We do have something like that for our continuous integration set-up: https://github.com/bazelbuild/continuous-integration/blob/master/base/docker_pull.bzl. Not really happy because we are using docker which is non deterministic, but we couldn't find something better.
