### ISSUE TITLE
compile.sh fails silently on Cygwin

### ISSUE THREAD

**Issue by dimo414** [google/bazel#128]
(tl;dr see the bulleted list at the bottom)

I just tried to see if I could get Bazel working in Cygwin, which isn't mentioned positively or negatively in [the FAQ](http://bazel.io/FAQ.html#what-about-windows), and `compile.sh` appears to fail silently.

```
$ echo $JAVA_HOME
/cygdrive/c/Program Files/Java/jdk1.8.0_45

$ javac -version
javac 1.8.0_45

$ apt-cyg install libarchive-devel pkg-config zip gcc-g++ zlib-devel
Package libarchive-devel is already installed, skipping
Package pkg-config is already installed, skipping
Package zip is already installed, skipping
Package gcc-g++ is already installed, skipping
Package zlib-devel is already installed, skipping

$ ./compile.sh

$ echo $?
127
```

Tweaking `compile.sh` to be verbose reveals that the failure is on [this line](https://github.com/google/bazel/blob/ff6458cdeb9/compile.sh#L215):

```
JAVAC_VERSION=$($JAVAC -version 2>&1)
```

Because `$JAVAC` is not quoted and `$JAVA_HOME` contains a space.  Escaping the space (i.e. `JAVA_HOME=".../Program\ Files/..."`) causes `compile.sh` to report that "JAVA_HOME (/cygdrive/c/Program\ Files/Java/jdk1.8.0_45) is not a path to a working JDK."

Working around this by creating a symlink without a space, the script gets a little further:

```
$ ./compile.sh
Compiling Java stubs for protocol buffers...
./compile.sh: line 362: : command not found
````

This is [line 362](https://github.com/google/bazel/blob/ff6458cdeb9/compile.sh#L362); at least this time the error is helpful, but it seems like there's a missing `-x $PROTOC` earlier in the script.

Sadly setting `$PROTOC` gets us to a real sticking point:

```
$ ./compile.sh
Compiling Java stubs for protocol buffers...
Compiling Bazel Java code...
javac: file not found: \tmp\bazel.236AM5Pv\param (The system cannot find the path specified)
```

This error is coming from `javac`, since it doesn't know how to handle Cygwin paths.  Addressing that is probably more invasive, but the earlier issues seem straightforward enough to address, namely:

* Failures in `$(...)` subshells can cause the script to fail silently.
* Calls to `$JAVAC` (and presumably other commands) need to be quoted to handle paths with spaces.
* `$PROTOC` is not checked for existence before being used.

**Comment by ulfjack** [comment]
We're happy to accept a patch. :-)

**Comment by damienmg** [comment]
I have submitted a commit for the JAVAC issue. I will work on the two others right now.

As Ulf said, if you have patch for cygwin, we would more than happy to integrate them.

**Comment by damienmg** [comment]
For the failures in $(...) I don't have a good solution that doesn't requires over-engineering what should stay a bootstrap script. I will add the check for the protobuf compiler though.

**Comment by dimo414** [comment]
Awesome, thanks Damien!  I was starting on a patch when I saw your comments, and found a *reasonably* painless solution to the `$(...)` failures.  According to [this question](http://unix.stackexchange.com/questions/23026/how-can-i-get-bash-to-exit-on-backtick-failure-in-a-similar-way-to-pipefail) subshells actually don't cause exits generally (which might actually be a problem elsewhere); they only fail in assignments i.e. `abc=$(...)`.  You can either use `abc=$(...) || true` to let the command always pass, or `abc=$(...) || fail ...` to fail verbosely.

That said, you may not need this workaround if you've fixed the quoting issue, it only cropped up because `[[ -x $JAVAC ]]` implicitly quotes the argument (apparently).

Since you're already on top of these specific problems, I don't have any patches to share presently, but I'll be sure to do so when I can.

**Comment by hanwen** [comment]
thanks for report. Keep the patches/bugreports coming!  I believe Bazel has supported cygwin in a distant past, so if your entire toolchain is on Cygwin, you could probably make this work.
