### ISSUE TITLE
./compile.sh fails with macports

### ISSUE THREAD

**Issue by allenporter** [google/bazel#142]
Following the instructions at http://bazel.io/docs/install.html for a Mac using macports, I get:
<pre>
$ ./compile.sh 
cp: /include/archive.h: No such file or directory
cp: /include/archive_entry.h: No such file or directory
</pre>

This seems to fix the problem:

<pre>
$ git diff ./compile.sh 
diff --git a/compile.sh b/compile.sh
index c4ff9bf..3a9231a 100755
--- a/compile.sh
+++ b/compile.sh
@@ -99,7 +99,8 @@ EOF
 
       elif [[ -e $macports_header ]]; then
         # For use with Macports.
-        archive_dir=$(dirname $(dirname $macports_header)) rm -f fromhost/*.[ah]
+        archive_dir=$(dirname $(dirname $macports_header))
+        rm -f fromhost/*.[ah]
         touch fromhost/empty.c
         cp "${archive_dir}"/include/{archive.h,archive_entry.h} fromhost/
         cp "${archive_dir}"/lib/{libarchive,liblzo2,liblzma,libcharset,libbz2,libxml2,libz,libiconv}.a \
</pre>

**Comment by damienmg** [comment]
Nice catch. Can you submit your patch with a github pull request?

**Comment by allenporter** [comment]
OK, I sent a pull request.  I haven't done that before, so let me know if anything is fishy.

**Comment by hanwen** [comment]
https://github.com/google/bazel/commit/e93638335955ff8d7e948f2d385319e458ee0ca4
