### ISSUE TITLE
Support Target Visibility in Skylark rules

### ISSUE THREAD

**Issue by schroederc** [google/bazel#144]
For Skylark rules, there doesn't seem to be a way to alter a specific target's visibility other than using the coarse-grained `package(default_visibility = [...])` declaration.

**Comment by laszlocsomor** [comment]
Can you explain what you tried and didn't work? I just tried adding `visibility = ['//visibility:private']` to a skylark rule instance and it worked as expected.

**Comment by schroederc** [comment]
Ah, my mistake.  `visibility` is indeed an inherent attribute on rules.  I was confused because I forgot to thread it through a macro.

Can Bazel improve their documentation about this?  `name` is an obvious attribute that each rule gets, but are there any more?  Only some of this list is correct for Skylark rules: http://bazel.io/docs/build-encyclopedia.html#common-attributes.  `licenses`, `data`, and `distribs` do not work.

**Comment by hanwen** [comment]
laurent, ping?

**Comment by laurentlb** [comment]
This was fixed
https://github.com/google/bazel/commit/6d450dc530ef7d9348dfd3830857a67014b7392f
