### ISSUE TITLE
config_setting ignores CROSSTOOL's 'compiler'

### ISSUE THREAD

**Issue by kayasoze** [google/bazel#148]
Attempts to predicate configurations on the value of this parameter seem to fail.  In my case, this value is implicitly set in CROSSTOOL rather than on the command line.

**Comment by ulfjack** [comment]
Probably requires treatment similar to CPU, which is also implicitly set in the CROSSTOOL file (if not specified).

**Comment by gregestren** [comment]
This should be pretty straightforward. Going to put in support this now...
