### ISSUE TITLE
bazel query 'kind(maven_jar, deps(//src/...))' returns emptyset

### ISSUE THREAD

**Issue by damienmg** [google/bazel#151]
Set the bazel repository to use a maven_jar with guava, and here the following results: it is confusing because we don't know the kind of rule we expect. Using the bind rules actually return results but that is a bit confusing. Either we should document the behavior (and what is the type of @guava-repo//jar:jar?)

$ bazel query 'kind(maven_jar, deps(//src/...))'
INFO: Empty results
$ bazel query 'deps(//src/...)' | grep guava
//third_party:guava/guava-18.0.jar
//third_party:guava/LICENSE
//third_party:guava-testlib
//third_party:guava/guava-testlib.jar
//external:guava
@guava-repo//jar:jar
@guava-repo//jar:guava-18.0.jar
$ bazel query 'kind(maven_jar, //external:*)'
//external:guava-repo

**Comment by kchodorow** [comment]
For reference, @guava-repo//jar:jar is a java_import.  I'll look into improving/documenting though.

**Comment by damienmg** [comment]
What is guava-18.0.jar ? 
$ bazel query 'kind(java_*, deps(//external:guava))'
@guava-repo//jar:jar
$ bazel query 'deps(//external:guava)' | grep guava
//external:guava
@guava-repo//jar:jar
@guava-repo//jar:guava-18.0.jar

**Comment by kchodorow** [comment]
It's a file.

**Comment by kchodorow** [comment]
Follow up: I don't think it makes sense for maven_jar, local_repository, etc. to be dependencies of a build.  It's a bit like saying "your project directory" is a dependency of //foo:bar.  I could special-case Bazel to consider the repository a dependency of any rule in the repository, but for now I'm just going to update the query docs.

For your [question](https://github.com/google/bazel/issues/151#issuecomment-94838978), you can always use --output label_kind to find out what type a dep is.

**Comment by damienmg** [comment]
I never said it wasn't making sense the way it is now but the documentation should explain what to expect there :)
