### ISSUE TITLE
http_jars are not visible to the //external package and cannot be bound

### ISSUE THREAD

**Issue by ekuefler** [google/bazel#153]
Per the documentation at http://bazel.io/docs/build-encyclopedia.html#http_jar, I have the following lines in my WORKSPACE:

```
http_jar(
  name = "guava-http-jar",
  url = "http://central.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.jar",
  sha256 = "d664fbfc03d2e5ce9cab2a44fb01f1d0bf9dfebeccc1a473b1f9ea31f79f6f99",
)
bind(
  name = "guava-http",
  actual = "@guava-http-jar//jar:guava-18.0.jar",
)
```

Attempting to depend on `//external:guava-http` gives me the following error:
```
ERROR: /Users/erik/github/Master/WORKSPACE:865:1: Target '@guava-http-jar//jar:guava-18.0.jar' is not visible from target '//external:guava-http'. Check the visibility declaration of the former target if you think the dependency is legitimate.
```

`http_jar` does not accept the `visibility` attribute, so I don't appear to have a way to remedy this.

The guava jar here is just an example of a publicly-accessible jar (I'm aware of maven-jar), the failure is the same regardless of the jar I use.

**Comment by kchodorow** [comment]
Sorry, the documentation is incorrect.  You should be able to bind `@guava-http-jar//jar`:

```
bind(
  name = "guava-http",
  actual = "@guava-http-jar//jar",
)
```

I'll fix it.

**Comment by ekuefler** [comment]
Thanks, confirmed that it works with that path. Keeping this open just for the doc fix.
