### ISSUE TITLE
Expose SelectorValue's dictionary

### ISSUE THREAD

**Issue by claridge** [google/bazel#154]
Macro-wrapping of rules doesn't work very well with selectors because the selector's contents are inaccessible. E.g. if I'm wrapping cc_library with a macro that adds a fixed set of options to copts, there's no way to properly handle the case in which copts is a selector.

If SelectorValue's dictionary were accessible, then it would be easy to perform these wrappings by creating new selectors as needed.

(My current workaround is to pass a dict instead of a selector in this case, but it creates asymmetry for the fields that don't need this special treatment.)

**Comment by ulfjack** [comment]
We certainly want to allow passing select through macros, but I'm not sure
if or how we'd allow access to the data. Note that we recently changed
select to allow combinations of selects with select and non-select
expressions (select() + select() + []).

Make sure to grab the latest version of the code, there are still changes
coming to Skylark as well as to select. ;-)

**Comment by claridge** [comment]
Nice! That should take care of the example I mentioned, but I've got another use case that I don't think is covered. I'm using header-tracking rules essentially the same as laurentlb described in https://groups.google.com/d/msg/bazel-discuss/RF0jVbXdUJg/tv1ve6UFk3IJ. That technique isn't compatible with using a selector for "deps" because you have to add a suffix to each target name.

**Comment by hanwen** [comment]
now that we have access to the native a provider (ctx.cc.transitive_headers) is this still relevant?

**Comment by damienmg** [comment]
Closing that bug. Feel free to ping for reopening if the bug is still relevant.
