### ISSUE TITLE
Bazel build fails at linker stage for a gtest test: ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by byuksel** [google/bazel#158]
Mac 10.9.5, installed GoogleTest 1.7.0

Simple test mydir/mytest.cc
#include <gtest/gtest.h>

TEST(MyTestSuitName, MyTestCaseName) {
  int actual = 1;
  EXPECT_GT(actual, 0);
  EXPECT_EQ(1, actual) << "Should be equal to one";
}

bazel test mydir:mytest fails with:
Undefined symbols for architecture x86_64:
  "testing::AssertionResult::AssertionResult(testing::AssertionResult const&)", referenced from:
      testing::AssertionResult testing::internal::CmpHelperGT<int, int>(char const*, char const*, int const&, int const&) in autocorrect-lib_test.pic.o
  "testing::AssertionFailure()", referenced from:
      testing::AssertionResult testing::internal::CmpHelpe
...
...
nced from:
      testing::AssertionResult testing::internal::CmpHelperEQ<int, int>(char const*, char const*, int const&, int const&) in autocorrect-lib_test.pic.o
  "testing::Message::GetString() const", referenced from:
      testing::AssertionResult::AppendMessage(testing::Message const&) in autocorrect-lib_test.pic.o
  "testing::internal::AssertHelper::operator=(testing::Message const&) const", referenced from:
      MyTestSuitName_MyTestCaseName_Test::TestBody() in autocorrect-lib_test.pic.o
  "typeinfo for testing::Test", referenced from:
      typeinfo for MyTestSuitName_MyTestCaseName_Test in autocorrect-lib_test.pic.o
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by byuksel** [comment]
Hacky fix:
It works when I pass the exact locations of gtest libraries to bazel:

bazel test --linkopt="/usr/local/lib/libgtest_main.a" --linkopt="/usr/local/lib/libgtest.a" mydir:mytest

**Comment by ulfjack** [comment]
The include in your example is missing (probably due to the '<', '>'). I assume you have the absolute path to the headers in there. The currently best way to import headers and libraries is to use the WORKSPACE file. I am not sure where the documentation for that is. Summoning Kristina to fill in the details.

**Comment by kchodorow** [comment]
Just added an example that demonstrates [using gtest with Bazel](http://bazel.io/docs/cpp.html#including-external-libraries-an-example).  It's not exactly what you're doing, as you can't actually use precompiled libraries as cc_ deps (yet).  Would this work for you?

**Comment by kchodorow** [comment]
Closing, let me know if this is still an issue.

**Comment by kianooshm** [comment]
@kchodorow: I've followed the instructions at http://bazel.io/docs/cpp.html#including-external-libraries-an-example.

Got linking problems until I manually changed this:
srcs = glob(["src/*.cc"], exclude = ["src/gtest-all.cc"])
to a manual list of .cc files under src/. Works well now.

**Comment by kchodorow** [comment]
Do you have the output with the linker errors around, still?

**Comment by kianooshm** [comment]
Sure:

INFO: Found 1 test target...
INFO: From Linking src/url-selector/url_cache_test:
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 0 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 1 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 2 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 3 has invalid symbol index 2
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 4 has invalid symbol index 11
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 5 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 6 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 7 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 8 has invalid symbol index 12
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 9 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 10 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 11 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 12 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 13 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 14 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 15 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 16 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 17 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 18 has invalid symbol index 13
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_info): relocation 19 has invalid symbol index 21
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_line): relocation 0 has invalid symbol index 2
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
bazel-out/local_linux-fastbuild/bin/src/url-selector/_objs/url_cache_test/src/url-selector/url_cache_test.pic.o: In function `TripleTest_HandlesPositiveInput_Test::TestBody()':
url_cache_test.cc:(.text+0x76): undefined reference to `testing::internal::EqFailure(char const*, char const*, std::string const&, std::string const&, bool)'
url_cache_test.cc:(.text+0xb5): undefined reference to `testing::Message::Message()'
url_cache_test.cc:(.text+0xe7): undefined reference to `testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)'
url_cache_test.cc:(.text+0xf2): undefined reference to `testing::internal::AssertHelper::operator=(testing::Message const&) const'
url_cache_test.cc:(.text+0xfa): undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
url_cache_test.cc:(.text+0x10c): undefined reference to `testing::internal::IsTrue(bool)'
url_cache_test.cc:(.text+0x136): undefined reference to `testing::internal::IsTrue(bool)'
url_cache_test.cc:(.text+0x176): undefined reference to `testing::AssertionSuccess()'
url_cache_test.cc:(.text+0x214): undefined reference to `testing::internal::AssertHelper::~AssertHelper()'
url_cache_test.cc:(.text+0x226): undefined reference to `testing::internal::IsTrue(bool)'
url_cache_test.cc:(.text+0x24c): undefined reference to `testing::internal::IsTrue(bool)'
bazel-out/local_linux-fastbuild/bin/src/url-selector/_objs/url_cache_test/src/url-selector/url_cache_test.pic.o: In function `TripleTest_HandlesPositiveInput_Test::~TripleTest_HandlesPositiveInput_Test()':
url_cache_test.cc:(.text._ZN36TripleTest_HandlesPositiveInput_TestD2Ev[_ZN36TripleTest_HandlesPositiveInput_TestD5Ev]+0xf): undefined reference to `testing::Test::~Test()'
bazel-out/local_linux-fastbuild/bin/src/url-selector/_objs/url_cache_test/src/url-selector/url_cache_test.pic.o: In function `TripleTest_HandlesPositiveInput_Test::~TripleTest_HandlesPositiveInput_Test()':
url_cache_test.cc:(.text._ZN36TripleTest_HandlesPositiveInput_TestD0Ev[_ZN36TripleTest_HandlesPositiveInput_TestD0Ev]+0x13): undefined reference to `testing::Test::~Test()'
bazel-out/local_linux-fastbuild/bin/src/url-selector/_objs/url_cache_test/src/url-selector/url_cache_test.pic.o: In function `testing::internal::TestFactoryImpl<TripleTest_HandlesPositiveInput_Test>::CreateTest()':
url_cache_test.cc:(.text._ZN7testing8internal15TestFactoryImplI36TripleTest_HandlesPositiveInput_TestE10CreateTestEv[_ZN7testing8internal15TestFactoryImplI36TripleTest_HandlesPositiveInput_TestE10CreateTestEv]+0x17): undefined reference to `testing::Test::Test()'
bazel-out/local_linux-fastbuild/bin/src/url-selector/_objs/url_cache_test/src/url-selector/url_cache_test.pic.o: In function `_GLOBAL__sub_I_url_cache_test.cc':
url_cache_test.cc:(.text.startup+0x47): undefined reference to `testing::internal::GetTestTypeId()'
url_cache_test.cc:(.text.startup+0x78): undefined reference to `testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)'
bazel-out/local_linux-fastbuild/bin/src/url-selector/_objs/url_cache_test/src/url-selector/url_cache_test.pic.o:(.data.rel.ro._ZTI36TripleTest_HandlesPositiveInput_Test[_ZTI36TripleTest_HandlesPositiveInput_Test]+0x10): undefined reference to `typeinfo for testing::Test'
bazel-out/local_linux-fastbuild/bin/src/url-selector/_objs/url_cache_test/src/url-selector/url_cache_test.pic.o:(.data.rel.ro._ZTV36TripleTest_HandlesPositiveInput_Test[_ZTV36TripleTest_HandlesPositiveInput_Test]+0x20): undefined reference to `testing::Test::SetUp()'
bazel-out/local_linux-fastbuild/bin/src/url-selector/_objs/url_cache_test/src/url-selector/url_cache_test.pic.o:(.data.rel.ro._ZTV36TripleTest_HandlesPositiveInput_Test[_ZTV36TripleTest_HandlesPositiveInput_Test]+0x28): undefined reference to `testing::Test::TearDown()'
collect2: error: ld returned 1 exit status

**Comment by kianooshm** [comment]
Gtest binaries can take a number of arguments, e.g., --gtest_output=xml will produce an xml report which I need for integration with CI. Is there a way to pass such flags to the test binary via bazel?

The only way of passing flags that is documented with bazel is passing c++ compiler and linker flags, not flags to the test program.

**Comment by kchodorow** [comment]
You should be able to use [args](http://bazel.io/docs/build-encyclopedia.html#test.args).

**Comment by kianooshm** [comment]
Thanks. But the value is not something known/fixed at time of writing the BUILD file; it's something to be passed in at time of invoking the test (by the CI).

For now I skip "bazel test" and just "bazel build" the test code and manually run the produced binary. Am I missing something important by not using "bazel test" ?

**Comment by kchodorow** [comment]
You should be able to specify `--test_arg=--gtest_output=xml`, see http://bazel.io/docs/bazel-user-manual.html#flag--test_arg.

**Comment by kchodorow** [comment]
Oh, and one thing you miss out on using build-and-invoke vs. `bazel test` is caching: `bazel test` won't rerun a test if its inputs haven't changed, so manually forcing all of your tests to run each time probably wastes some time.

**Comment by kianooshm** [comment]
I tried <b>--test_arg=--gtest_output=xml</b> with bazel test, but no luck:

This command:
*** <b>bazel test --test_arg="--gtest_output=xml:a.xml" my_test</b>
Produces a.xml somewhere deep in bazel-out/... (actually where the default test_detail.xml is).

This command:
*** <b>bazel-bin/my_test --gtest_output=xml:a.xml</b>
Produces a.xml in the current working directory (or whatever dir I specify).

**Comment by kchodorow** [comment]
"bazel test" runs the test in the runfiles tree (so bazel-bin/my_test.runfiles).

Sorry for the late response!

**Comment by Huzuri** [comment]
> I tried --test_arg=--gtest_output=xml with bazel test, but no luck:
> 
> This command:
> *** bazel test --test_arg="--gtest_output=xml:a.xml" my_test
> Produces a.xml somewhere deep in bazel-out/... (actually where the default test_detail.xml is).
> 
> This command:
> *** bazel-bin/my_test --gtest_output=xml:a.xml
> Produces a.xml in the current working directory (or whatever dir I specify).

it doesn't work in general this way, no output seems to be there....

**Comment by wondfor** [comment]
> 

did you solved this problem？I have the same trouble.
