### ISSUE TITLE
completion in zsh?

### ISSUE THREAD

**Issue by byzhang** [google/bazel#163]
I tried to use the bash completion script
```
autoload bashcompinit
bashcompinit
source /path/to/bazel-complete.bash
```
But when I press tab after 
```
output/bazel build //sc
```
Here is the error
```
_bazel__get_cword:local:1: not valid in this context: //sc
_bazel__get_command:1: unrecognized modifier `C'
_bazel__complete_stdout:local:11: not valid in this context: canonicalize-flags
_bazel__get_cword:local:1: not valid in this context: //sc
_bazel__get_command:1: unrecognized modifier `C'
_bazel__complete_stdout:local:11: not valid in this context: canonicalize-flags
_bazel__get_cword:local:1: not valid in this context: //sc
_bazel__get_command:1: unrecognized modifier `C'
_bazel__complete_stdout:local:11: not valid in this context: canonicalize-flags
_bazel__get_cword:local:1: not valid in this context: //sc
_bazel__get_command:1: unrecognized modifier `C'
_bazel__complete_stdout:local:11: not valid in this context: canonicalize-flags
```
I'm no means of a bash/zsh expert, so I'm creating this issue to see whether you or some experts can see and have some suggestions/solutions.

**Comment by damienmg** [comment]
Ok I did most of the script in Bash and I am in no way a zsh expert (always used bash). This script relies heavily on bash features (scripts/bazel-complete-template.bash) but the information for building the script from bazel should be generic (you can get them doing `bazel help completion`). If someone is good with zsh then he can adapt the bazel-complete-template.bash to create a zsh version.

We have a zsh version internally so if a googler feel like doing it he can open-source the one we have.

**Comment by damienmg** [comment]
schroederc is going to do it. For some reason I cannot assign it outside of the bazel team so assigning to myself

**Comment by damienmg** [comment]
Some files are missing next update will add them, sorry for that.
