### ISSUE TITLE
Allow exporting hdrs without filename extensions

### ISSUE THREAD

**Issue by kalakris** [google/bazel#164]
I was trying to package a library which contains header files without extensions, and I wanted to export just a subset of them. However, when I listed these headers in a hdrs attribute of a cc_library...
```
hdrs = ["my_stl/vector", "my_stl/array"]
```
...I got the following error:
```
ERROR: /home/mrinal/bazel_test/my_stl/BUILD:64:12: in hdrs attribute of cc_library rule //my_stl:my_stl: file '//my_stl:my_stl/vector' is misplaced here (expected .h, .hh, .hpp, .hxx or .inc).
ERROR: /home/mrinal/bazel_test/my_stl/BUILD:64:12: in hdrs attribute of cc_library rule //my_stl:my_stl: '//my_stl:my_stl/vector' does not produce any cc_library hdrs files (expected .h, .hh, .hpp, .hxx or .inc).
```

It would be nice to either (1) allow header files without extensions, since this is a fairly common case encountered in the wild, or (2) allow customizing the list of allowed extensions per file type in the cc_library rule.

**Comment by ulfjack** [comment]
We actually allow any file in hdrs internally. We didn't want to do that from the beginning, but random extensions are not that uncommon, so it seems like we need to revisit that decision.

**Comment by fzakaria** [comment]
Just thought I'd open this:
You made the change to 'hdrs' which is only for "public"

I've come across some repositories (i.e. gflags ) that use different extensions for internal-only header files.
Perhaps this needs to be more lax in general. I'm not sure why bazel makes assumptions on the extension since we are providing the file format to the properties.

**Comment by lberki** [comment]
I think you're actually right, but IIRC we have a bunch of places where some extensions are hard-coded into Bazel, or at least that's a few references to CppFilesTypes.CPP_SOURCE would suggest. @ulfjack  ?

**Comment by ulfjack** [comment]
Yeah, for files in srcs we need to know whether they're actually sources or headers. We could consider re-designing cc_* to have another attribute for internal headers, so we don't need to switch on extension, but it's unfortunately a bigger change.

**Comment by ddwolf** [comment]
I am running this problem now.
I am converting an existing project which is built by make. this project contains some header files whose names end with `.map`. So is there a solution for this?

**Comment by finn-ball** [comment]
+1 having a similar issue

**Comment by jiemingwang** [comment]
It will be nice to support such requiremment. Many large projects include header files that don't have extensions. e.g., QT project uses class names as the header file names. Can this be done with command line options?
