### ISSUE TITLE
subtractive pattern cannot exclude bazel itself

### ISSUE THREAD

**Issue by kayasoze** [google/bazel#166]
It appears that Bazel's output directory includes pre-substitution BUILD files which are evaluated before the subtractive pattern is processed, leading to errors such as:

```
~/workspace ❯❯❯ bazel build -- third-party/... -third-party/bazel/...
ERROR: .../workspace/third-party/bazel/output-common/classes/BUILD:87:1: //third-party/bazel/output/classes:srcs: invalid label 'autovalue/shaded/com/google/common/auto/common/MoreElements$1.class' in element 72 of attribute 'srcs' in 'filegroup' rule: invalid target name 'autovalue/shaded/com/google/common/auto/common/MoreElements$1.class': target names may not contain '$'.
ERROR: package contains errors: third-party/bazel/output/classes.
ERROR: error loading package 'third-party/bazel/output/classes': Package 'third-party/bazel/output/classes' contains errors.
```

**Comment by kayasoze** [comment]
Generally, it appears that any subdirectory of the workspace may not contain a file named BUILD with invalid characters, even if the BUILD file is semantically to be unrelated to bazel (e.g. data/construction-costs/BUILD).  Does the concept of a .bazelignore file exist?

**Comment by ulfjack** [comment]
There's no .bazelignore or similar. So yes, BUILD files need to be valid if
they exist. That said, I think we've recently fixed the compile.sh script
for bazel not to put BUILD files into the output/ directory. Do you have
the latest source?

**Comment by kayasoze** [comment]
I do not have the latest source; I'll reopen if this continues to be an issue.
