### ISSUE TITLE
bazel doesn't build on CentOS 6

### ISSUE THREAD

**Issue by huahang** [google/bazel#172]
When I was trying to build bazel on CentOS 6, I got the following error:

    src/main/cpp/blaze.cc: In function ‘std::string blaze::GetInstallBase(const string&, const string&)’:
    src/main/cpp/blaze.cc:210:39: error: ‘archive_read_free’ was not declared in this scope
       retval = archive_read_free(blaze_zip);
                                           ^
    src/main/cpp/blaze.cc: In function ‘void blaze::ActuallyExtractData(const string&, const string&)’:
    src/main/cpp/blaze.cc:825:39: error: ‘archive_read_free’ was not declared in this scope
       retval = archive_read_free(blaze_zip);
                                           ^

It seems that the libarchive-devel package shipped with CentOS 6 is too old?

**Comment by ulfjack** [comment]
On Thu, Apr 30, 2015 at 10:31 AM, huahang <notifications@github.com> wrote:

> When I was trying to build bazel on CentOS 6, I got the following error:
>
> src/main/cpp/blaze.cc: In function ‘std::string blaze::GetInstallBase(const string&, const string&)’:
> src/main/cpp/blaze.cc:210:39: error: ‘archive_read_free’ was not declared in this scope
>    retval = archive_read_free(blaze_zip);
>                                        ^
> src/main/cpp/blaze.cc: In function ‘void blaze::ActuallyExtractData(const string&, const string&)’:
> src/main/cpp/blaze.cc:825:39: error: ‘archive_read_free’ was not declared in this scope
>    retval = archive_read_free(blaze_zip);
>                                        ^
>
> It seems that the libarchive-devel package shipped with CentOS 6 is too
> old?
>

You're in a better position to answer that question... What version is it?

We've been considering ways of removing the libarchive dependency, either
by using the zip reader implementation from ijar, which we also ship, or
from the JDK. It's not ready yet, though.

**Comment by huahang** [comment]
I believe it is the version 2.8.3 of libarchive that ships with CentOS 6. It is too old for bazel right now. It would be great if this dependency could be removed. :-)

**Comment by ulfjack** [comment]
That's ancient. The new function has been there since February 2010. You
can try replacing archive_read_free with archive_read_finish and see if
that works.

**Comment by hanwen** [comment]
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-discuss/HB5p5fSrI24/M69ZlY0z4k4J for instructoins for RHEL 5. Does that work for Centos 6 ?

**Comment by huahang** [comment]
@ulfjack Replacing archive_read_free() with archive_read_finish() works for CentOS 6. But it causes a warning in Ubuntu 14.04. Since archive_read_finish() is just a deprecated synonym for archive_read_free() introduced with libarchive 3.0 according to http://manpages.ubuntu.com/manpages/saucy/man3/archive_read_free.3.html, can we just use archive_read_finish() for libarchive version lower than 3.0 and archive_read_free() for 3.0 and above? I code review of this idea has been submitted in gerrit and please have a look. :-)

https://bazel-review.googlesource.com/#/c/1300

**Comment by hanwen** [comment]
fixed by https://github.com/google/bazel/commit/eb6e90397eff1083f0574b6cbd94eb9f42d2d239
