### ISSUE TITLE
Different source code list for different operating system?

### ISSUE THREAD

**Issue by huahang** [google/bazel#173]
In some BUILD file examples, I see that we can use config_setting+select to do different things for different CPU architectures, like the following:

    config_setting(
        name = "x86_64",
        values = {"cpu": "k8"},
    )

But how can we do that for different operating systems?

**Comment by ulfjack** [comment]
In Bazel, we currently use the cpu to also encode the operating system.
This is suboptimal, and we're looking to change that, but it's the best I
can offer right now.

**Comment by pspeter3** [comment]
Is there any update on this now?

**Comment by kchodorow** [comment]
We haven't made any changes to this yet.  What are you trying to do?

**Comment by pspeter3** [comment]
We're trying to vendor node but pick the precompiled version based on OS architecture since we don't want to compile node every time as well.
