### ISSUE TITLE
select() + list fails in common cases

### ISSUE THREAD

**Issue by claridge** [google/bazel#176]
I've found a couple cases where adding a list to a select() doesn't work. Both of these fail with the error "'+' operator applied to incompatible types".

Can't add an empty list:
  s = select({
      "foo": ["FOO"],
      "bar": ["BAR"],
  }) + []

Can't add sums of lists:
  s = select({
      "foo": ["FOO"],
      "bar": ["BAR"],
  }) + (["A"] + ["B"])
This also doesn't work if the sum is stored in a variable:
  L = (["A"] + ["B"])
  s = select({
      "foo": ["FOO"],
      "bar": ["BAR"],
  }) + L
But it does work if you add a copy of L (via L[:], list(L), etc.).

**Comment by claridge** [comment]
Also: performing select() addition in a BUILD with selectors generated in .bzl file is buggy. For example, this works:
    s = select({"//conditions:default": ["foo"]}) + ["bar"]
But if I define
   def make_select():
       return select({"//conditions:default": ["foo"]}) + ["bar"]
in a .bzl file, and then
    s = make_select() + ["bar"]
in a BUILD file, I get an incompatible types error.

**Comment by damienmg** [comment]
Isn't this the same as https://github.com/google/bazel/issues/176?

**Comment by claridge** [comment]
This is #176. :)

**Comment by damienmg** [comment]
Arf sorry wanted to ask about #121.

**Comment by claridge** [comment]
I don't think so. The empty list example still fails if I replace `[]` with `list([])`. Also, in the sum example, `print(type(L))` shows the lowercase `list`.

I'm not sure how to inspect types for the addition-in-a-BUILD-file problem.

(I just modified my example for the BUILD file, BTW. The old one was still valid but had an unnecessary list in make_select().)

**Comment by gregestren** [comment]
Can you provide more context for the example from your first message (i.e. not the make_select example, which I've isolated)? Is all that logic defined within a Skylark rule?

**Comment by claridge** [comment]
The examples in the first message are from Skylark macros. For example, define

def trigger_error():
  s = select({
      "foo": ["FOO"],
      "bar": ["BAR"],
  }) + []

and then call trigger_error() within a BUILD file.

**Comment by gregestren** [comment]
Thanks for the clarification. I've got a fix which I *think* addresses all your cases (but since you mentioned a variety of them, please test when pushed and let us know if anything remains wonky).

Thank you for your patience!

**Comment by claridge** [comment]
I've been a little bogged down, but I'll try this out as soon as I get a chance. Thanks for the quick attention!
