### ISSUE TITLE
Execute a cc_binary target in genrule?

### ISSUE THREAD

**Issue by huahang** [google/bazel#180]
In my custom build process, I would like to execute a cc_binary target in a genrule. If possible, how can I do that in bazel? Thanks!

**Comment by kchodorow** [comment]
Add it under "tools" and then use $(location), basically the first example
here: http://bazel.io/docs/build-encyclopedia.html#genrule_examples.  Use
your cc_binary target ($(location //foo:bar)) instead of create_foo.pl.

**Comment by huahang** [comment]
@kchodorow thanks!
