### ISSUE TITLE
Formulation of proper -I flag in copts

### ISSUE THREAD

**Issue by applmak** [google/bazel#181]
The documentation for how to properly formulate the path passed to -I is unclear. What is the right make-variable to use in order to get these paths to begin with bazel-out?

**Comment by kchodorow** [comment]
You could use $(location ...), but in general you probably shouldn't need to set -I (you'd add the path to includes=[...]).  What are you trying to do?

**Comment by applmak** [comment]
I'm trying to compile a library that has some private includes. I don't want to add them to includes=[] because of the transitive nature of the parameter. How would I use location in this manner? Can I refer to arbitrary directories (such as $(location include/)) or only labels?

**Comment by huahang** [comment]
I have the same question too. When I try the $(location ...) method, I get the following error:

in copts attribute of cc_library rule //openssl:openssl: '$location' syntax is not supported; use '$(location)' instead for "Make" variables, or escape the '$' as '$$' if you intended this for the shell.

What is the right way to use it?

**Comment by ulfjack** [comment]
There's $(GENDIR), which ought to work for this purpose.

**Comment by applmak** [comment]
Does bazel-genfiles always contain the relevant source tree files as well? I thought it only contained generated files?

**Comment by ulfjack** [comment]
Well, you can set -Ix/y/z -I$(GENFILES)/x/y/z.

**Comment by applmak** [comment]
Oh, duh, I get what you are saying. Bazel runs with the cwd @ the same place as the WORKSPACE file. Gotcha. Thanks.

**Comment by huahang** [comment]
@ulfjack That works indeed. But it implies that the BUILD file's location has got to be fixed relative to the WORKSPACE root, right?

**Comment by ulfjack** [comment]
Yes. It might be nicer to support something like $(location), but we don't
have that at this time.

(We also don't have relative labels, which might be an even bigger obstacle
to relocatable BUILD files.)

**Comment by shahms** [comment]
With the recent changes to the directory layout, $(GENDIR) no longer works, leaving no way of specifying a correct '-I' parameter.  The only documented Make variables are BINDIR and GENDIR, neither of which point anywhere.

TBH, that was a bit of a hack in the first place to work around proper $(location) support for `copts`.

**Comment by ulfjack** [comment]
Why can't you use includes?

**Comment by shahms** [comment]
Because I don't want to transitively infect all of the targets which depend on this one.  Specifically, in this case it's a BUILD file for an external dependency (gflags) configured via CMake.  Among other artifacts, CMake spits out `include/gflags/config.h` which is a "private" header (listed in the BUILD `srcs`) alongside the public headers.  Clients should include those headers as `<gflags/header.h>` but the library source includes `config.h` as `"config.h"`.  We've added `includes = ["include"]` and an unsightly, but formerly functional, `-I$(GENDIR)/repo_name/include/gflags` to `copts`.  Given the nature of the problem, adding the nested `include/gflags` to `includes` ends up sacrificing correctness for expedience and potentially causing more, harder to debug, problems down the road.

**Comment by vchigrin** [comment]
I think that this issue should be re-opened. Specifying  paths from the root of workspace is not always a good solution (e.g. if you wrapped cc_library target creation in a macro and want to add addional -I options in it). Having something like $(CURRENT_SOURCE_DIR) and $(CURRENT_GEN_DIR) would be very helpful. 
Using "includes" attribute is not always possible - as mentioned earlier it have transitive nature, causing weird build failures if some directories have headers with the same name.

**Comment by oliverdain** [comment]
> e.g. if you wrapped cc_library target creation in a macro

I am in exactly this situation and don't see a workaround.

**Comment by evantorrie** [comment]
> I'm trying to compile a library that has some private includes. I don't want to add them to includes=[] because of the transitive nature of the parameter. How would I use location in this manner? Can I refer to arbitrary directories (such as $(location include/)) or only labels?

This newly added commit may be of interest, adding a `implementation_deps` attribute to C++ rules.  Not currently in an official bazel release, but looks like it may help with this issue.

https://github.com/bazelbuild/bazel/commit/2875a25fd0913a4c30d566693bd95c848a67a844

**Comment by PandaBlueYellow** [comment]
Could you make $(SRCS) available also to copt?
