### ISSUE TITLE
Support linker script dependencies in cc rules

### ISSUE THREAD

**Issue by claridge** [google/bazel#184]
"deps" should allow linker scripts to be included. See https://groups.google.com/d/topic/bazel-discuss/Hl3L0cFfkoM/discussion for more info.

I think this is a blocker for Makani.

**Comment by ulfjack** [comment]
I think this is as simple as changing cc_library to allow .lds files in deps (at least that'll match what we allow internally) in BazelCppRuleClasses.java line 449.

**Comment by llolly** [comment]
llolly2000@hotmail.com

**Comment by claridge** [comment]
Do you mind if (a) the .ld extension is accepted as well, and if (b) I take a stab at this myself?

**Comment by claridge** [comment]
I went ahead and took a shot at it - https://bazel-review.googlesource.com/#/c/1262/. I pinged laurentlb about reviewing.

**Comment by ulfjack** [comment]
I added some comments to the code review.

**Comment by hanwen** [comment]
https://github.com/google/bazel/commit/de189ba8cbcde2623ff0daf022cf5784ebcd35a5
