### ISSUE TITLE
More verbose test failure output

### ISSUE THREAD

**Issue by mikedanese** [google/bazel#190]
Is there a way to get more verbose test output?

When I run `bazel test`
```
➜  libkubernetes git:(master)# bazel test //test                              
INFO: Found 1 test target...
FAIL: //test:test (see /home/miked/.cache/bazel/_bazel_miked/f4f1511ac3aadf22b22f6857b29e43da/libkubernetes/bazel-out/local_linux-fastbuild/testlogs/test/test/test.log).
Target //test:test up-to-date:
  bazel-bin/test/test
INFO: Elapsed time: 0.235s, Critical Path: 0.01s
//test:test                                                              FAILED

Executed 1 out of 1 tests: 1 fails locally.
```

This output is not very useful to me. When I run the test binary directly I get more useful test output:

```
➜  libkubernetes git:(master)# ./bazel-out/local_linux-fastbuild/bin/test/test
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from MyTest
[ RUN      ] MyTest.thing
test/unit/my_test.cc:4: Failure
Value of: 2
Expected: 1
[  FAILED  ] MyTest.thing (0 ms)
[----------] 1 test from MyTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] MyTest.thing

 1 FAILED TEST
```

For reference, I am testing in this repo https://github.com/mikedanese/libkubernetes

**Comment by janakdr** [comment]
Have you tried --test_output=errors? (Same result as cat-ing the test log
file whose location is printed using the default settings.)

**Comment by mikedanese** [comment]
Awesome! Exactly what I was looking for. Thanks!

**Comment by lnunno** [comment]
Adding this to the docs/tutorial somewhere would be fantastic.

**Comment by apelisse** [comment]
is there a way to make this the default (config, env)?

**Comment by mikedanese** [comment]
@apelisse in your .bazelrc you can add
```
test --test_output=errors
```

e.g. here: https://github.com/kubernetes/kubernetes/blob/master/.bazelrc#L3

**Comment by datoga** [comment]
Any way to get colors on the output?

**Comment by datoga** [comment]
I answer my self:

bazel test --test_output=errors **--action_env="GTEST_COLOR=1"** ...
