### ISSUE TITLE
bazel fetch //... in workspace without tools directory fails

### ISSUE THREAD

**Issue by davidzchen** [google/bazel#192]
Running `bazel fetch //...` in a workspace that has no tools directory even though `~/.bazelrc` points to the workspace under the Bazel installation directory:

```
❯❯❯ bazel fetch //...
ERROR: no such package 'tools/jdk': BUILD file not found on package path.
```

**Comment by damienmg** [comment]
You mean that the installation is in the package_path, right?

**Comment by damienmg** [comment]
Fetch doesn't seems to take the package path in consideration

**Comment by davidzchen** [comment]
Yes, I am using the `.bazelrc` generated by `compile.sh`.

**Comment by damienmg** [comment]
Does simply building works?

**Comment by kchodorow** [comment]
We need to add a fetch --package_path line to the .bazelrc, since the build line isn't used for fetch.

**Comment by damienmg** [comment]
Right can you update the compile.sh and documentation then?

**Comment by davidzchen** [comment]
Adding a `fetch --package_path` line to `.bazelrc` fixes the problem. Thanks!

**Comment by davidzchen** [comment]
I have opened PR #195 for the fix in compile.sh.
