### ISSUE TITLE
Native rules should expose Skylark providers

### ISSUE THREAD

**Issue by schroederc** [google/bazel#193]
Rules like cc_library/java_library should expose Skylark providers.  Then Skylark rules can interoperate, and for instance, link against C++ libraries and compile with their headers.

**Comment by davidzchen** [comment]
+1 this would be awesome to have.

Also discussed in the following thread: https://groups.google.com/forum/#!topic/bazel-discuss/vluCSjYArTA

**Comment by damienmg** [comment]
Technically this is a duplicate of #146
