### ISSUE TITLE
Add basename and dirname attributes to File

### ISSUE THREAD

**Issue by davidzchen** [google/bazel#194]
As discussed in the following thread: https://groups.google.com/forum/#!topic/bazel-discuss/zxC3fT9f-t8

Skylark rules frequently involve getting the `basename` and `dirname` of a `File`. Currently, the best way to do so is by relying on the shell using `"$(dirname " + file.path + ")"` and `"$(basename " + file.path + ")"`, which is not ideal.

It would be good to either provide utility functions or add `basename` and `dirname` to `File`. The latter might be the simpler approach.

**Comment by laurentlb** [comment]
Implemented
