### ISSUE TITLE
Base workspace appears to be broken

### ISSUE THREAD

**Issue by ademuri** [google/bazel#202]
Using bazel at head, in a clean workspace, building an example, I get the following error:

```
$ $BAZEL_BIN build examples/java-native/src/main/java/com/example/myproject:hello-world
ERROR: /home/adam/bazel/base_workspace/tools/defaults/BUILD:19:1: no such target '//tools/jdk:extdir': target 'extdir' not declared in package 'tools/jdk' defined by /home/adam/bazel/base_workspace/tools/jdk/BUILD and referenced by '//tools/defaults:javac_extdir'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.452s
```

**Comment by damienmg** [comment]
Do you have only the examples in your workspace? What about the tools directory in your package_path? Is it up to date?

**Comment by hanwen** [comment]
I am seeing this too, but only in a repository where the tools/ directory came from an older bazel version.

**Comment by ademuri** [comment]
Ok, pulled down a fresh copy of bazel and it's working now. Looks like a version skew error. Thanks for the quick response!
