### ISSUE TITLE
--package_path suggestion is unusable with other maven packages

### ISSUE THREAD

**Issue by hanwen** [google/bazel#204]
trying to compile grpc using its included BUILD file:

[hanwen@pomba grpc]$ bazel build :all
ERROR: /home/hanwen/vc/grpc/BUILD:129:10: Label '//:src/core/security/credentials_win32.c' crosses boundary of subpackage 'src' (have you deleted src/BUILD? If so, use the --deleted_packages=src option).
ERROR: /home/hanwen/vc/grpc/BUILD:577:10: Label '//:src/cpp/common/call.cc' crosses boundary of subpackage 'src' (have you deleted src/BUILD? If so, use the --deleted_packages=src option).

This breaks because bazel sees the src/ directory from the bazel source code, and grpc has a src/ directory too.

Instead of pointing package_path to the bazel source tree, we should generate a tree (maybe using symlinks?) with just the tools/ directory, so the rest of our package (third_party, src, etc.) doesn't interfere with third party packages. 

Alternatively, we should generate a binary package, which would include a usable //tools directory.

**Comment by kchodorow** [comment]
We do generate a "clean" tree in base_workspace with just tools/, third_party/, and examples/, which is what (any recent version of) ./compile.sh generates.  What does your .bazelrc look like?

**Comment by hanwen** [comment]
ah! that explains it (it wires in the bazel toplevel directory). my bad
