### ISSUE TITLE
bazel test appears to ignore --run_under

### ISSUE THREAD

**Issue by kayasoze** [google/bazel#206]
This is in contrast to bazel run, which appears to honor it.

Instead, bazel test appears to run tests under tools/test/test-setup.sh.

**Comment by kayasoze** [comment]
My use case is that I'd like to run cross-compiled tests by wrapping them in a tool which executes them under the correct target architecture.

**Comment by hanwen** [comment]
I'll have a look. the flag was copied from the google internal code base, but I'm not sure the functionality was.

**Comment by kayasoze** [comment]
It's a fantastically useful flag--I'd vote for keeping it, if possible.  It enables:

* running tests under Valgrind or other instrumenting tool
* easily running a test target on multiple architectures (e.g. on both natively and on an embedded device via a --run_under shim).

**Comment by hanwen** [comment]
@kayasoze  - I agree with you. It was an oversight

**Comment by kayasoze** [comment]
Fantastic!  Thanks so much!

If I may mention one small nit: the arguments passed into the run_under script vary slightly depending on whether `bazel run` or `bazel test` was used.  In the former case, the absolute path to the test binary is passed; in the latter case, the path is relative to the current working directory.

**Comment by hanwen** [comment]
that's possilbe. They're separate code paths. If this a problem, can you open a separate bug?
