### ISSUE TITLE
Workspace status files don't contain much useful data

### ISSUE THREAD

**Issue by lberki** [google/bazel#210]
stable-status.txt and volatile-status.txt only contain --embed_label.

It would be nice if they actually contained something useful (hostname, username, current time...)

**Comment by damienmg** [comment]
Assignig to Lukacs for tracking the bug. Reassign at will :)

**Comment by damienmg** [comment]
It is actually somehow a duplicate of #216. At least the fix Ming sent is addressing this issue.
