### ISSUE TITLE
Web status server runtime error while displaying 'query' commands

### ISSUE THREAD

**Issue by schroederc** [google/bazel#215]
When running `bazel --use_webstatusserver=8080 query //...`, the client-side Javascript will throw the following runtime error:

`Uncaught TypeError: Cannot read property 'length' of null` from `index.js:34`

This is caused by `j.targets` being `null` because the `WebStatusEventCollector` only sets the target list during `BuildStartingEvents` which are not published during a `query`.

**Comment by lberki** [comment]
How annoying is this? Sounds like a minor bug I'll get around fixing _eventually_. If it causes an unexpected amount of pain, let me know.
