### ISSUE TITLE
OSX: Bazel doesn't compile

### ISSUE THREAD

**Issue by bhickey** [google/bazel#223]
This might be a regression with the latest version of Xcode.
I'm on OS X 10.10.4 with Xcode 6.2 / Build version 6C131e and using the JDK 8 update 45

````
➜  bazel git:(master) git reset --hard origin/master
HEAD is now at 662166f Initial checkin of the "mobile-install" command.
➜  bazel git:(master) ./compile.sh 
Compiling Java stubs for protocol buffers...
Compiling Bazel Java code...
Extracting helper classes for Bazel Java...
Creating libblaze.jar...
Compiling SingleJar tool code...
Extracting helper classes for SingleJar tool...
Creating SingleJar_deploy.jar...
Compiling JavaBuilder tool code...
Extracting helper classes for JavaBuilder tool...
Creating JavaBuilder_deploy.jar...
Compiling client .cc files...
Linking client...
Compiling ijar .cc files...
Linking ijar...
Compiling JNI libraries...
Linking libunix.dylib...
Compiling build-runfiles...
Compiling process-wrapper...
Creating Bazel self-extracting archive...
Creating objc helper tools...
Compiling actoolzip code...
Extracting helper classes for actoolzip...
Creating precomp_actoolzip_deploy.jar...
Compiling ibtoolzip code...
Extracting helper classes for ibtoolzip...
Creating precomp_ibtoolzip_deploy.jar...
Compiling momczip code...
Extracting helper classes for momczip...
Creating precomp_momczip_deploy.jar...
Compiling bundlemerge code...
Extracting helper classes for bundlemerge...
Creating precomp_bundlemerge_deploy.jar...
Compiling plmerge code...
Extracting helper classes for plmerge...
Creating precomp_plmerge_deploy.jar...
Compiling xcodegen code...
Extracting helper classes for xcodegen...
Creating precomp_xcodegen_deploy.jar...
Extracting Bazel installation...
..........
ERROR: /Users/brendan/dev/bazel/output/classes/BUILD:87:1: //output/classes:srcs: invalid label 'autovalue/shaded/com/google/common/auto/common/MoreElements$1.class' in element 80 of attribute 'srcs' in 'filegroup' rule: invalid target name 'autovalue/shaded/com/google/common/auto/common/MoreElements$1.class': target names may not contain '$'.
ERROR: package contains errors: output/classes.
ERROR: error loading package 'output/classes': Package 'output/classes' contains errors.
````

**Comment by damienmg** [comment]
Hello,

Can you try to remove the 'output' folder and try again?
Le lun. 1 juin 2015 à 01:36, Brendan Hickey <notifications@github.com> a
écrit :

> This might be a regression with the latest version of Xcode.
> I'm on OS X 10.10.4 with Xcode 6.2 / Build version 6C131e and using the
> JDK 8 update 45
>
> ➜  bazel git:(master) git reset --hard origin/master
> HEAD is now at 662166f Initial checkin of the "mobile-install" command.
> ➜  bazel git:(master) ./compile.sh
> Compiling Java stubs for protocol buffers...
> Compiling Bazel Java code...
> Extracting helper classes for Bazel Java...
> Creating libblaze.jar...
> Compiling SingleJar tool code...
> Extracting helper classes for SingleJar tool...
> Creating SingleJar_deploy.jar...
> Compiling JavaBuilder tool code...
> Extracting helper classes for JavaBuilder tool...
> Creating JavaBuilder_deploy.jar...
> Compiling client .cc files...
> Linking client...
> Compiling ijar .cc files...
> Linking ijar...
> Compiling JNI libraries...
> Linking libunix.dylib...
> Compiling build-runfiles...
> Compiling process-wrapper...
> Creating Bazel self-extracting archive...
> Creating objc helper tools...
> Compiling actoolzip code...
> Extracting helper classes for actoolzip...
> Creating precomp_actoolzip_deploy.jar...
> Compiling ibtoolzip code...
> Extracting helper classes for ibtoolzip...
> Creating precomp_ibtoolzip_deploy.jar...
> Compiling momczip code...
> Extracting helper classes for momczip...
> Creating precomp_momczip_deploy.jar...
> Compiling bundlemerge code...
> Extracting helper classes for bundlemerge...
> Creating precomp_bundlemerge_deploy.jar...
> Compiling plmerge code...
> Extracting helper classes for plmerge...
> Creating precomp_plmerge_deploy.jar...
> Compiling xcodegen code...
> Extracting helper classes for xcodegen...
> Creating precomp_xcodegen_deploy.jar...
> Extracting Bazel installation...
> ..........
> ERROR: /Users/brendan/dev/bazel/output/classes/BUILD:87:1: //output/classes:srcs: invalid label 'autovalue/shaded/com/google/common/auto/common/MoreElements$1.class' in element 80 of attribute 'srcs' in 'filegroup' rule: invalid target name 'autovalue/shaded/com/google/common/auto/common/MoreElements$1.class': target names may not contain '$'.
> ERROR: package contains errors: output/classes.
> ERROR: error loading package 'output/classes': Package 'output/classes' contains errors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/bazel/issues/223>.
>
-- 
Damien

**Comment by bhickey** [comment]
That did it. Thanks.
