### ISSUE TITLE
missing dependency declaration checks fail on relative paths

### ISSUE THREAD

**Issue by kayasoze** [google/bazel#226]
I have a third-party, binary cross-compiler checked into my repository under "tools/cpp/foo".  The toolchain is hardcoded to live in /usr/local/foo, so I create a symlink in /usr/local to the appropriate location in build tree.  Unfortunately, cxx_builtin_include_directory must include the "real" (resolved) path or Bazel will print "rule is missing dependency declarations" errors when cross compiling.  The real path, however, can vary depending on the location of my source tree.  This makes it difficult to share the CROSSTOOL file between users or agents.  Ideally I'd be able to specify cxx_builtin_include_directory relative to my workspace root with a substitution, or perhaps Bazel could attempt to follow symlinks before issuing the error.

**Comment by kayasoze** [comment]
An alternative solution would be to allow cxx_builtin_include_directory to reference paths that are either relative to the workspace or relative to tools/cpp.

**Comment by hanwen** [comment]
it is already supports relative paths. Are you sure you're setting -isystem flags so the headers are found as relative paths too?

**Comment by kayasoze** [comment]
From what I can tell, cxx_builtin_include_directory paths do not translate into -isystem flags.  However, Bazel has the ability to monitor filesystem access, and so complains with "rule is missing dependency declarations" when cxx_builtin_include_directory paths include symlinks.  

The missing dependencies are, in fact, specified in correctly cxx_builtin_include_directory, but Bazel uses their absolute paths when checking and not their symlink paths.   Using relative paths may work, but as I'd rather not root my cross compiler within the Bazel source tree's tools/cpp, the relative paths also include a symlink, and so still confuses Bazel's strict dependency checks.

**Comment by hanwen** [comment]
that is my point: you may have to specify -isystem paths separately, so headers are found as relative paths.

**Comment by hanwen** [comment]
I think your compiler cannot find its system headers normally, and uses the path at /proc/self/exe (which is absolute) to discover system headers. IIRC Clang does this.

AFAICT, this is working as intended.  Please reopen if you have further issues.

**Comment by kayasoze** [comment]
Even when system include paths are made relative using -isystem and -iprefix (and verified as relative using gcc -v and strace) Bazel identifies the files only by their fully qualified paths for the purposes of dependency declaration checking.  

It appears that Bazel does preserve symlinks in the paths properly (it doesn't resolve them itself via readlink(), which is what you'd expect with a syscall shim), so the issue is that Bazel fully qualifies the file paths, likely by simply prepending the path from the root to the workspace.  It's still important to verify the absolute path, but perhaps the string compare should be performed on file paths which have both been fully qualified (e.g. with realpath or similar).

**Comment by hanwen** [comment]
can you provide a reproduction scenario?

**Comment by kayasoze** [comment]
Unfortunately I cannot share my cross compiler.  I attempted to reproduce the scenario using an installed version of gcc 4.9.2 on Ubuntu, but that particular compiler uses readlink() and so always opens files using absolute paths.  That exhibits a bug, but in a different form--in my case the compiler is opening files using relative paths and the complaint is that the relative path (which is a suffix of the absolute path) doesn't match the absolute path.  In this latter case, the compiler is using absolute paths and cxx_builtin_include_directory references the relative path, which is not a suffix of the absolute path, so the match still fails.  

The latter bug can be reproduced by applying this patch to CROSSTOOL, copying it and BUILD into tools/cpp/unresolved, creating a symlink into /, and building the cpp examples using --crosstool_top.

$ ls -l tools/cpp/unresolved                                                                                                                                              
total 20
-rw-rw-r-- 1 vn vn 2022 Jun 18 17:02 BUILD
-rw-rw-r-- 1 vn vn 8297 Jun 19 15:34 CROSSTOOL
lrwxrwxrwx 1 vn vn    1 Jun 18 17:07 root -> /

diff --git a/tools/cpp/CROSSTOOL b/tools/cpp/unresolved/CROSSTOOL
index d49a9b1..2228173 100644
--- a/tools/cpp/CROSSTOOL
+++ b/tools/cpp/unresolved/CROSSTOOL
@@ -34,34 +34,37 @@ toolchain {
   target_system_name: "local"
   toolchain_identifier: "local_linux"

-  tool_path { name: "ar" path: "/usr/bin/ar" }
-  tool_path { name: "compat-ld" path: "/usr/bin/ld" }
-  tool_path { name: "cpp" path: "/usr/bin/cpp" }
-  tool_path { name: "dwp" path: "/usr/bin/dwp" }
-  tool_path { name: "gcc" path: "/usr/bin/gcc" }
+  tool_path { name: "ar" path: "root/usr/bin/ar" }
+  tool_path { name: "compat-ld" path: "root/usr/bin/ld" }
+  tool_path { name: "cpp" path: "root/usr/bin/cpp" }
+  tool_path { name: "dwp" path: "root/usr/bin/dwp" }
+  tool_path { name: "gcc" path: "root/usr/bin/gcc" }
   cxx_flag: "-std=c++0x"
+  cxx_flag: "-v"
+  cxx_flag: "--prefix=tools/cpp/unresolved/root/usr/"
+  cxx_flag: "--sysroot=tools/cpp/unresolved/root/"
   linker_flag: "-lstdc++"
-  linker_flag: "-B/usr/bin/"
+  linker_flag: "-Broot/usr/bin/"

   # TODO(bazel-team): In theory, the path here ought to exactly match the path
   # used by gcc. That works because bazel currently doesn't track files at
   # absolute locations and has no remote execution, yet. However, this will need
   # to be fixed, maybe with auto-detection?
-  cxx_builtin_include_directory: "usr/lib/gcc/"
-  cxx_builtin_include_directory: "usr/local/include"
-  cxx_builtin_include_directory: "usr/include"
-  tool_path { name: "gcov" path: "/usr/bin/gcov" }
+  cxx_builtin_include_directory: "root/usr/lib/gcc/"
+  cxx_builtin_include_directory: "root/usr/local/include"
+  cxx_builtin_include_directory: "root/usr/include"
+  tool_path { name: "gcov" path: "root/usr/bin/gcov" }

   # C(++) compiles invoke the compiler (as that is the one knowing where
   # to find libraries), but we provide LD so other rules can invoke the linker.
-  tool_path { name: "ld" path: "/usr/bin/ld" }
+  tool_path { name: "ld" path: "root/usr/bin/ld" }

-  tool_path { name: "nm" path: "/usr/bin/nm" }
-  tool_path { name: "objcopy" path: "/usr/bin/objcopy" }
+  tool_path { name: "nm" path: "root/usr/bin/nm" }
+  tool_path { name: "objcopy" path: "root/usr/bin/objcopy" }
   objcopy_embed_flag: "-I"
   objcopy_embed_flag: "binary"
-  tool_path { name: "objdump" path: "/usr/bin/objdump" }
-  tool_path { name: "strip" path: "/usr/bin/strip" }
+  tool_path { name: "objdump" path: "root/usr/bin/objdump" }
+  tool_path { name: "strip" path: "root/usr/bin/strip" }
 }

**Comment by hanwen** [comment]
can you confirm that the .d files created by the compiler contain relative paths?

You can find them by running "blaze build -s " and looking for a -MD foo/bar.d option to GCC/Clang

**Comment by kayasoze** [comment]
In my example above, they do not:

```
$ cat ~/.cache/bazel/_bazel_vn/2f1d8f18c8c8e37f4dad743ff8530c4d/bazel/bazel-out/local_linux-fastbuild/bin/tools/cpp/_objs/malloc/tools/cpp/empty.pic.d
bazel-out/local_linux-fastbuild/bin/tools/cpp/_objs/malloc/tools/cpp/empty.pic.o: \
 tools/cpp/empty.cc /usr/include/stdc-predef.h
```

However, the compiler itself has learned a relative include path for stdc-predef.h; from gcc -v:

```
#include "..." search starts here:
 .
#include <...> search starts here:
 tools/cpp/unresolved/root/usr/include
 tools/cpp/unresolved/root/usr/include/c++/4.9
 tools/cpp/unresolved/root/usr/include/x86_64-linux-gnu/c++/4.9
 tools/cpp/unresolved/root/usr/include/c++/4.9/backward
 /usr/lib/gcc/x86_64-linux-gnu/4.9/include
 tools/cpp/unresolved/root/usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed
 tools/cpp/unresolved/root/usr/include/x86_64-linux-gnu
```

It appears that gcc is turning my relative path into an absolute path via readlink; from strace -f:

```
[pid 18364] readlink("/home/vn/src/bazel/tools/cpp/unresolved/root", "/", 4095) = 1
```

From the above example, and my own experience with a cross-compiler, it appears that:

* some modern versions of gcc will turn relative paths into absolute paths for open() (as on Ubuntu 15.04), at least when there is a symlink in the path
* other (cross) compilers will use relative paths for open(), possibly even if the path contains a symlink
* in both of the above cases, bazel may be tricked into thinking a particular dependency has not been declared because of a path mismatch

**Comment by hanwen** [comment]
Have you tried the -no-canonical-prefixes option for GCC ?

**Comment by kayasoze** [comment]
-no-canonical-prefixes improves neither the cross compiler case nor the "local Ubuntu GCC accessed with a relative path" case (patched avove).  The behavior is the same.

**Comment by kayasoze** [comment]
Actually, in the relative compiler case, --no-canonical-prefixes actually does work, as long as the CROSSTOOL file is at the top of the cross-compiler tree.  This is the case that I care about, so I'm closing this issue.  You fine folks have enough to do already.
