### ISSUE TITLE
Unknown Bazel startup option: '--bazelrc=/dev/null'.

### ISSUE THREAD

**Issue by joeltornatore** [google/bazel#229]
The documentation describes using --bazelrc to specify a configuration file, but bazel does not recognize that option.

The documentation:
<i>Bazel looks for an optional configuration file in the location specified by the --bazelrc=file option</i>

When used:
<code>$ bazel --bazelrc=/dev/null build //projects/shared:java-lib
Unknown Bazel startup option: '--bazelrc=/dev/null'.</code>

Bazel does support --blazerc (blaze, not bazel).

**Comment by kianooshm** [comment]
I got the same problem ...

**Comment by damienmg** [comment]
Did you sync recently?

**Comment by kianooshm** [comment]
Thanks for the swift response. I haven't. Using "blazerc" for now.

**Comment by damienmg** [comment]
The --bazelrc command was added 20 days ago and I added yesterday the
--nomaster_bazelrc one so it should be all fixed now.
