### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by schroederc** [google/bazel#230]
```
$ bazel build //src:bazel
ERROR: <redacted>/bazel/tools/build_rules/genproto.bzl:60:3: every rule of type gensrcjar implicitly depends upon the target '//external:jar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
ERROR: <redacted>/bazel/tools/build_rules/genproto.bzl:60:3: every rule of type gensrcjar implicitly depends upon the target '//external:jar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
ERROR: <redacted>/bazel/tools/build_rules/genproto.bzl:60:3: every rule of type gensrcjar implicitly depends upon the target '//external:jar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
ERROR: <redacted>/bazel/tools/build_rules/genproto.bzl:60:3: every rule of type gensrcjar implicitly depends upon the target '//external:jar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
ERROR: <redacted>/bazel/tools/build_rules/genproto.bzl:60:3: every rule of type gensrcjar implicitly depends upon the target '//external:jar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
ERROR: <redacted>/bazel/tools/build_rules/genproto.bzl:60:3: every rule of type gensrcjar implicitly depends upon the target '//external:jar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
WARNING: errors encountered while analyzing target '//src:bazel': it will not be built.
INFO: Found 0 targets...
ERROR: execution phase succeeded, but there were loading phase errors.
INFO: Elapsed time: 0.241s, Critical Path: 0.00s
```

**Comment by damienmg** [comment]
You need to rebuild bazel with compile.sh. We should not expect more of
those kind of change in the future.
Le ven. 5 juin 2015 à 18:44, Cody Schroeder <notifications@github.com> a
écrit :

> $ bazel build //src:bazel
> ERROR: <redacted>/bazel/tools/build_rules/genproto.bzl:60:3: every rule of type gensrcjar implicitly depends upon the target '//external:jar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
> ERROR: <redacted>/bazel/tools/build_rules/genproto.bzl:60:3: every rule of type gensrcjar implicitly depends upon the target '//external:jar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
> ERROR: <redacted>/bazel/tools/build_rules/genproto.bzl:60:3: every rule of type gensrcjar implicitly depends upon the target '//external:jar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
> ERROR: <redacted>/bazel/tools/build_rules/genproto.bzl:60:3: every rule of type gensrcjar implicitly depends upon the target '//external:jar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
> ERROR: <redacted>/bazel/tools/build_rules/genproto.bzl:60:3: every rule of type gensrcjar implicitly depends upon the target '//external:jar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
> ERROR: <redacted>/bazel/tools/build_rules/genproto.bzl:60:3: every rule of type gensrcjar implicitly depends upon the target '//external:jar',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
> WARNING: errors encountered while analyzing target '//src:bazel': it will not be built.
> INFO: Found 0 targets...
> ERROR: execution phase succeeded, but there were loading phase errors.
> INFO: Elapsed time: 0.241s, Critical Path: 0.00s
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/bazel/issues/230>.
>
-- 
Damien

**Comment by schroederc** [comment]
A newer version does fix it.
