### ISSUE TITLE
`git_repository` and `new_git_repository`

### ISSUE THREAD

**Issue by davidzchen** [google/bazel#234]
It would be useful to have workspace rules that clone a git repository at a given commit hash if provided for binding or turning into a Bazel repository respectively. This is especially useful for depending on third party projects that are hosted in git repositories but do not necessarily have source releases that could be used for `http_archive` or `new_http_archive`.

Currently, the alternative is to use git submodule, which is more cumbersome.

**Comment by damienmg** [comment]
Kristina: is that still on your roadmap?

**Comment by kchodorow** [comment]
Yes, it just hasn't been a priority.

**Comment by davidzchen** [comment]
Mind if I take a shot at this?

**Comment by kchodorow** [comment]
Feel free!

**Comment by davidzchen** [comment]
Completed in commit deb003fae0e0da7d45156f5ea0b36900aa9e5790
