### ISSUE TITLE
Preserve permissions when http_archive unzips

### ISSUE THREAD

**Issue by kchodorow** [google/bazel#238]
If you zip up an executable and then download/extract it via [new_]http_archive, the "executable" ends up with 644, even if running `unzip thing.zip` results in a 755.

**Comment by kchodorow** [comment]
I thought this would be an easy fix, but unfortunately the Apache Commons compress library refuses to return the permissions.  The zip's central directory header has the permission set in the external file attributes, but `zipFileEntry.getExternalAttributes()` returns 0.  I've sent a message to user@commons.apache.org about it, waiting to see what they say.

**Comment by damienmg** [comment]
Can you use the SingleJar zip library instead?

On Wed, Jun 10, 2015 at 4:13 PM Kristina <notifications@github.com> wrote:

> I thought this would be an easy fix, but unfortunately the Apache Commons
> compress library refuses to return the permissions. The zip's central
> directory header has the permission set in the external file attributes,
> but zipFileEntry.getExternalAttributes() returns 0. I've sent a message
> to user@commons.apache.org about it, waiting to see what they say.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/bazel/issues/238#issuecomment-110768716>.
>
-- 
Damien
