### ISSUE TITLE
Build break?

### ISSUE THREAD

**Issue by huahang** [google/bazel#245]
I get the following error when I am trying to build bazel from the latest code.

    $ ./compile.sh 
    INFO: You can skip this first step by providing a path to the bazel binary as second argument:
    INFO:    ./compile.sh build /path/to/bazel
    🍃  Building Bazel from scratch...........
    🍃  Building Bazel with Bazel.
    .Extracting Bazel installation...
    Sending SIGTERM to previous Bazel server (pid=1890)... done.
    ......
    INFO: Found 1 target...
    INFO: From Javac src/java_tools/buildjar/libskylark-deps.jar [for host]:
    /bin/bash: line 2: jar: command not found
    /bin/bash: line 4: jar: command not found
    javac: no source files
    Usage: javac <options> <source files>
    use -help for a list of possible options
    ERROR: /data/users/huahang/src/bazel/src/java_tools/buildjar/BUILD:171:1: error executing shell command: 'set -e;rm -rf bazel-out/host/bin/src/java_tools/buildjar/libskylark-deps.jar.build_output bazel-out/host/bin/src/java_tools/buildjar/libskylark-deps.jar.build_java bazel-out/host/bin/src/java_tools...' failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 2.
    Target //src:bazel failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 3.470s, Critical Path: 1.10s

    Building output/bazel

**Comment by damienmg** [comment]
It means that it does not found the jar command.  I will fix that today.

**Comment by damienmg** [comment]
reproduced: remove jar from PATH and clean compile.sh

**Comment by huahang** [comment]
Just curious, I think the jar command is in my PATH?

    $ which jar
    /data/users/huahang/opt/jdk/linux-x64/jdk1.8/bin/jar

**Comment by damienmg** [comment]
Huh but it is probably not in the path that Bazel is using.

**Comment by huahang** [comment]
No, I don't. And it builds if I copy a jar binary in `/usr/bin`. Yet still, I think I would be nicer if the `jar` command could be loaded from `$JAVA_HOME`.

Thank you! :-)

**Comment by damienmg** [comment]
The fix to use the jar from JAVA_HOME is in our internal source repository and should be in a few hours :)

**Comment by lisendong** [comment]
@damienmg  why you only add "/usr/bin or /usr/local/bin" to "$PATH" when running compile.sh ???

I think you should use system's PATH variable .

or how cound I modify the  PATH variable ???

**Comment by jin** [comment]
@lisendong This issue is closed, do you mind creating a new issue with the details of your problem?

**Comment by lisendong** [comment]
when I install bazel by compile.sh:
```
ERROR: /tmp/bazel_Bcmpd1a6/out/external/googleapis/BUILD.bazel:127:1: error executing shell command: 'cp 'bazel-out/k8-opt/bin/external/googleapis/google_watch_v1_java_grpc_srcs.jar' 'bazel-out/k8-opt/bin/external/googleapis/google_watch_v1_java_grpc_srcs.srcjar'' failed (Exit 127): bash failed: error executing command
  (cd /tmp/bazel_Bcmpd1a6/out/execroot/io_bazel && \
  exec env - \
  /bin/bash -c 'cp '\''bazel-out/k8-opt/bin/external/googleapis/google_watch_v1_java_grpc_srcs.jar'\'' '\''bazel-out/k8-opt/bin/external/googleapis/google_watch_v1_java_grpc_srcs.srcjar'\''')
/bin/bash: cp: command not found
Target //src:bazel failed to build
```
