### ISSUE TITLE
Permission denied building ijar

### ISSUE THREAD

**Issue by rsteiger** [google/bazel#259]
steigerwald-macbookair:Projects steigerwald$ git clone https://github.com/google/bazel.git
Cloning into 'bazel'...
remote: Counting objects: 31216, done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 31216 (delta 16), reused 0 (delta 0), pack-reused 31153
Receiving objects: 100% (31216/31216), 52.47 MiB | 5.63 MiB/s, done.
Resolving deltas: 100% (18302/18302), done.
Checking connectivity... done.
steigerwald-macbookair:Projects steigerwald$ cd bazel/
steigerwald-macbookair:bazel steigerwald$ ./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch...........
🍃  Building Bazel with Bazel.
.Extracting Bazel installation...
.........
INFO: Found 1 target...
INFO: From Linking tools/cpp/libmalloc.a:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: bazel-out/local_darwin-fastbuild/bin/tools/cpp/_objs/malloc/tools/cpp/empty.pic.o has no symbols
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for library: bazel-out/local_darwin-fastbuild/bin/tools/cpp/libmalloc.a the table of contents is empty (no object file members in the library define global symbols)
INFO: From Linking tools/cpp/libmalloc.a [for host]:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: bazel-out/host/bin/tools/cpp/_objs/malloc/tools/cpp/empty.o has no symbols
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for library: bazel-out/host/bin/tools/cpp/libmalloc.a the table of contents is empty (no object file members in the library define global symbols)
INFO: From Linking src/main/native/libunix.so:
ld: warning: option -noall_load is obsolete and being ignored
INFO: From Javac src/main/java/libshell-skylark.jar [for host]:
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
INFO: From Javac src/java_tools/buildjar/libskylark-deps.jar [for host]:
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
INFO: From Javac src/java_tools/singlejar/libbootstrap.jar [for host]:
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
INFO: From Javac src/java_tools/buildjar/libbootstrap.jar [for host]:
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
INFO: From Building src/main/java/libbazel-core.jar (1109 files):
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Target //src:bazel up-to-date:
  bazel-bin/src/bazel
INFO: Elapsed time: 85.782s, Critical Path: 81.23s

🍃  Building Bazel tools.
Building tools/jdk/ijar
/Users/steigerwald/Projects/bazel/output/bazel --nomaster_blazerc --blazerc=/dev/null build --singlejar_top=//src/java_tools/singlejar:bootstrap_deploy.jar --javabuilder_top=//src/java_tools/buildjar:bootstrap_deploy.jar --ijar_top=//third_party/ijar --javacopt=-source 1.7 -target 1.7 --stamp --embed_label head (@6e31316) //third_party/ijar:ijar
scripts/bootstrap/buildenv.sh: line 56: /Users/steigerwald/Projects/bazel/output/bazel: Permission denied
steigerwald-macbookair:bazel steigerwald$ 

And JAVA_HOME

steigerwald-macbookair:bazel steigerwald$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home

**Comment by damienmg** [comment]
Did you start from a clean clone? Do you have an "output" directory, what's
in it?
Le dim. 21 juin 2015 à 02:37, Richie Steigerwald <notifications@github.com>
a écrit :

> steigerwald-macbookair:Projects steigerwald$ git clone
> https://github.com/google/bazel.git
> Cloning into 'bazel'...
> remote: Counting objects: 31216, done.
> remote: Compressing objects: 100% (58/58), done.
> remote: Total 31216 (delta 16), reused 0 (delta 0), pack-reused 31153
> Receiving objects: 100% (31216/31216), 52.47 MiB | 5.63 MiB/s, done.
> Resolving deltas: 100% (18302/18302), done.
> Checking connectivity... done.
> steigerwald-macbookair:Projects steigerwald$ cd bazel/
> steigerwald-macbookair:bazel steigerwald$ ./compile.sh
> INFO: You can skip this first step by providing a path to the bazel binary
> as second argument:
> INFO: ./compile.sh build /path/to/bazel
> 🍃 Building Bazel from scratch...........
> 🍃 Building Bazel with Bazel.
> .Extracting Bazel installation...
> .........
> INFO: Found 1 target...
> INFO: From Linking tools/cpp/libmalloc.a:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool:
> file:
> bazel-out/local_darwin-fastbuild/bin/tools/cpp/_objs/malloc/tools/cpp/empty.pic.o
> has no symbols
> warning:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool:
> warning for library:
> bazel-out/local_darwin-fastbuild/bin/tools/cpp/libmalloc.a the table of
> contents is empty (no object file members in the library define global
> symbols)
> INFO: From Linking tools/cpp/libmalloc.a [for host]:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool:
> file: bazel-out/host/bin/tools/cpp/_objs/malloc/tools/cpp/empty.o has no
> symbols
> warning:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool:
> warning for library: bazel-out/host/bin/tools/cpp/libmalloc.a the table of
> contents is empty (no object file members in the library define global
> symbols)
> INFO: From Linking src/main/native/libunix.so:
> ld: warning: option -noall_load is obsolete and being ignored
> INFO: From Javac src/main/java/libshell-skylark.jar [for host]:
> warning: [options] bootstrap class path not set in conjunction with
> -source 1.7
> 1 warning
> INFO: From Javac src/java_tools/buildjar/libskylark-deps.jar [for host]:
> warning: [options] bootstrap class path not set in conjunction with
> -source 1.7
> 1 warning
> INFO: From Javac src/java_tools/singlejar/libbootstrap.jar [for host]:
> warning: [options] bootstrap class path not set in conjunction with
> -source 1.7
> 1 warning
> INFO: From Javac src/java_tools/buildjar/libbootstrap.jar [for host]:
> warning: [options] bootstrap class path not set in conjunction with
> -source 1.7
> 1 warning
> INFO: From Building src/main/java/libbazel-core.jar (1109 files):
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Target //src:bazel up-to-date:
> bazel-bin/src/bazel
> INFO: Elapsed time: 85.782s, Critical Path: 81.23s
>
> 🍃 Building Bazel tools.
> Building tools/jdk/ijar
> /Users/steigerwald/Projects/bazel/output/bazel --nomaster_blazerc
> --blazerc=/dev/null build
> --singlejar_top=//src/java_tools/singlejar:bootstrap_deploy.jar
> --javabuilder_top=//src/java_tools/buildjar:bootstrap_deploy.jar
> --ijar_top=//third_party/ijar --javacopt=-source 1.7 -target 1.7 --stamp
> --embed_label head (@6e31316
> <https://github.com/google/bazel/commit/6e31316>) //third_party/ijar:ijar
> scripts/bootstrap/buildenv.sh: line 56:
> /Users/steigerwald/Projects/bazel/output/bazel: Permission denied
> steigerwald-macbookair:bazel steigerwald$
>
> And JAVA_HOME
>
> steigerwald-macbookair:bazel steigerwald$ echo $JAVA_HOME
> /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/bazel/issues/259>.
>
-- 
Damien

**Comment by rsteiger** [comment]
Yes, I did a clean clone. Here's the output directory:

steigerwald-macbookair:bazel steigerwald$ ls -al output/
total 24000
drwxr-xr-x   3 steigerwald  5000       102 Jun 20 17:31 .
drwxr-xr-x  24 steigerwald  5000       816 Jun 20 17:31 ..
-rwxr-xr-x   1 steigerwald  5000  12285646 Jun 20 17:33 bazel

**Comment by damienmg** [comment]
What is the output of `file output/bazel`? The script basically say it
cannot execute it.
What happens if you do `./output/bazel info` ?

On Mon, Jun 22, 2015 at 2:41 AM Richie Steigerwald <notifications@github.com>
wrote:

> Yes, I did a clean clone. Here's the output directory:
>
> steigerwald-macbookair:bazel steigerwald$ ls -al output/
> total 24000
> drwxr-xr-x 3 steigerwald 5000 102 Jun 20 17:31 .
> drwxr-xr-x 24 steigerwald 5000 816 Jun 20 17:31 ..
> -rwxr-xr-x 1 steigerwald 5000 12285646 Jun 20 17:33 bazel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/bazel/issues/259#issuecomment-113973631>.
>
-- 
Damien

**Comment by rsteiger** [comment]
Here are the results of the commands:

steigerwald-macbookair:bazel steigerwald$ file output/bazel 
output/bazel: Mach-O 64-bit executable x86_64

steigerwald-macbookair:bazel steigerwald$ output/bazel info
Sending SIGTERM to previous Bazel server (pid=73810)... done.
...........
bazel-bin: /private/var/tmp/_bazel_steigerwald/3be305c2a4bf4c5fcb6748aabe2ab3fc/bazel/bazel-out/local_darwin-fastbuild/bin
bazel-genfiles: /private/var/tmp/_bazel_steigerwald/3be305c2a4bf4c5fcb6748aabe2ab3fc/bazel/bazel-out/local_darwin-fastbuild/genfiles
bazel-testlogs: /private/var/tmp/_bazel_steigerwald/3be305c2a4bf4c5fcb6748aabe2ab3fc/bazel/bazel-out/local_darwin-fastbuild/testlogs
command_log: /private/var/tmp/_bazel_steigerwald/3be305c2a4bf4c5fcb6748aabe2ab3fc/command.log
committed-heap-size: 128MB
execution_root: /private/var/tmp/_bazel_steigerwald/3be305c2a4bf4c5fcb6748aabe2ab3fc/bazel
gc-count: 3
gc-time: 27ms
install_base: /var/tmp/_bazel_steigerwald/install/e4b35ba04b14087b2d4838e2f6550331
max-heap-size: 1908MB
message_log: /private/var/tmp/_bazel_steigerwald/3be305c2a4bf4c5fcb6748aabe2ab3fc/message.log
output_base: /private/var/tmp/_bazel_steigerwald/3be305c2a4bf4c5fcb6748aabe2ab3fc
output_path: /private/var/tmp/_bazel_steigerwald/3be305c2a4bf4c5fcb6748aabe2ab3fc/bazel/bazel-out
package_path: %workspace%
release: release head (@6e31316)
server_pid: 74136
used-heap-size: 15MB
workspace: /Users/steigerwald/Projects/bazel

I forgot to mention before, I have the internal version of bazel working and running in a separate workspace.

**Comment by damienmg** [comment]
Is that consistent?
What happens if you try './compile.sh tools output/bazel'?

**Comment by rsteiger** [comment]
From a clean client I ran './compile.sh' and './compile.sh tools output/bazel'

The first fails when building the tools, the second one succeeds. 

steigerwald-macbookair:bazel steigerwald$ ./compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch...........
🍃  Building Bazel with Bazel.
.Extracting Bazel installation...
.......
INFO: Found 1 target...
INFO: From Building src/main/java/libpackages.jar (147 files):
Note: src/main/java/com/google/devtools/build/lib/packages/AspectDefinition.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
INFO: From Building src/main/java/libanalysis-exec-rules-skyframe.jar (540 files):
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
INFO: From Building src/main/java/libquery2.jar (46 files):
Note: src/main/java/com/google/devtools/build/lib/query2/BlazeTargetAccessor.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Target //src:bazel up-to-date:
  bazel-bin/src/bazel
INFO: Elapsed time: 40.902s, Critical Path: 37.94s

🍃  Building Bazel tools.
Building tools/jdk/ijar
/Users/steigerwald/bazel/output/bazel --nomaster_blazerc --blazerc=/dev/null build --singlejar_top=//src/java_tools/singlejar:bootstrap_deploy.jar --javabuilder_top=//src/java_tools/buildjar:bootstrap_deploy.jar --ijar_top=//third_party/ijar --javacopt=-source 1.7 -target 1.7 --stamp --embed_label head (@0e1680e) //third_party/ijar:ijar
scripts/bootstrap/buildenv.sh: line 56: /Users/steigerwald/bazel/output/bazel: Permission denied

steigerwald-macbookair:bazel steigerwald$ ./compile.sh tools output/bazel
🍃  Building Bazel tools...........
Build successful! Binary is here: output/bazel

steigerwald-macbookair:bazel steigerwald$ output/bazel build examples/cpp:hello-world
INFO: Found 1 target...
Target //examples/cpp:hello-world up-to-date:
  bazel-bin/examples/cpp/hello-world
INFO: Elapsed time: 0.532s, Critical Path: 0.39s

-------

From a clean client I ran './compile.sh &> /dev/null ; ls output/bazel' and got 'permission denied' again with the 'ls' command, but ran it a few seconds later and got the expected output--I suspect that it may be trying to run it before it finishes writing it to the disk.

I cloned head and tried again, but could not replicate. Perhaps it is fixed.

**Comment by damienmg** [comment]
Ok I will close the bug for now as unreproducible, please ping again if you find it.
