### ISSUE TITLE
Error: Could not find or load main class ...swiftstdlibtoolzip.SwiftStdlibToolZip

### ISSUE THREAD

**Issue by rsteiger** [google/bazel#260]
I created a simple swift project (https://gist.github.com/38579c1894f0bee07dd4) and am trying to build it, but running into the following error:

Richies-Air:base_workspace richie$ git clone https://gist.github.com/38579c1894f0bee07dd4.git swift ; bazel build //swift:SwiftTest --ios_sdk_version=8.3 --ios_simulator_version=8.3
Cloning into 'swift'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
Checking connectivity... done.
INFO: Found 1 target...
INFO: From SwiftStdlibCopy swift/SwiftTest.swiftstdlib.zip:
Error: Could not find or load main class com.google.devtools.build.xcode.swiftstdlibtoolzip.SwiftStdlibToolZip
ERROR: /Users/richie/Projects/bazel/base_workspace/swift/BUILD:1:1: null failed: java failed: error executing command /usr/bin/java -jar bazel-out/host/bin/tools/objc/swiftstdlibtoolzip_deploy.jar bazel-out/local_darwin-fastbuild/bin/swift/SwiftTest.swiftstdlib.zip Frameworks ... (remaining 5 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //swift:SwiftTest failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.484s, Critical Path: 3.10s

Richies-Air:base_workspace richie$ xcodebuild -version
Xcode 6.3.2
Build version 6D2105

Richies-Air:base_workspace richie$ bazel info
bazel-bin: /private/var/tmp/_bazel_richie/18f5c57b1aa69c14a4cd010219fe7073/bazel/bazel-out/local_darwin-fastbuild/bin
bazel-genfiles: /private/var/tmp/_bazel_richie/18f5c57b1aa69c14a4cd010219fe7073/bazel/bazel-out/local_darwin-fastbuild/genfiles
bazel-testlogs: /private/var/tmp/_bazel_richie/18f5c57b1aa69c14a4cd010219fe7073/bazel/bazel-out/local_darwin-fastbuild/testlogs
command_log: /private/var/tmp/_bazel_richie/18f5c57b1aa69c14a4cd010219fe7073/command.log
committed-heap-size: 202MB
execution_root: /private/var/tmp/_bazel_richie/18f5c57b1aa69c14a4cd010219fe7073/bazel
gc-count: 22
gc-time: 2190ms
install_base: /var/tmp/_bazel_richie/install/ed3a288aa2045eb1821b4059c1f6aec5
max-heap-size: 477MB
message_log: /private/var/tmp/_bazel_richie/18f5c57b1aa69c14a4cd010219fe7073/message.log
output_base: /private/var/tmp/_bazel_richie/18f5c57b1aa69c14a4cd010219fe7073
output_path: /private/var/tmp/_bazel_richie/18f5c57b1aa69c14a4cd010219fe7073/bazel/bazel-out
package_path: %workspace%:/Users/richie/Projects/bazel/base_workspace
release: release head (@10a84ef)
server_pid: 2858
used-heap-size: 53MB
workspace: /Users/richie/Projects/bazel

**Comment by Aragos** [comment]
Swift support is still very experimental and I would not rely on it working (it was only just added to bazel last week! :).
