### ISSUE TITLE
./compile.sh build failure creating objc dylib

### ISSUE THREAD

**Issue by kchodorow** [google/bazel#262]
Running on OS X from https://github.com/google/bazel/commit/1a8576a5dc8e0a1b04bcb230cc4f6c0f962fb8e4:

```
...
🍃  Building Bazel tools...........
Building tools/objc/StdRedirect.dylib
/Users/kchodorow/gitroot/bazel/output/bazel --nomaster_bazelrc --bazelrc=/dev/null build --singlejar_top=//src/java_tools/singlejar:bootstrap_deploy.jar --javabuilder_top=//src/java_tools/buildjar:bootstrap_deploy.jar --ijar_top=//third_party/ijar --javacopt=-source 1.7 -target 1.7 --stamp --embed_label head (@1a8576a) //src/tools/xcode/stdredirect:StdRedirect.dylib
____Loading package: src/tools/xcode/stdredirect
____Loading complete.  Analyzing...
____Found 1 target...
____From Executing genrule //src/tools/xcode/stdredirect:stdredirect_genrule:
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphonesimulator'
clang: warning: no such sysroot directory: ''
clang: warning: no such sysroot directory: ''
ld: building for iOS Simulator, but linking against dylib built for MacOSX file '/usr/lib/libSystem.dylib' for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: /Users/kchodorow/gitroot/bazel/src/tools/xcode/stdredirect/BUILD:4:1: Executing genrule //src/tools/xcode/stdredirect:stdredirect_genrule failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //src/tools/xcode/stdredirect:StdRedirect.dylib failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 0.557s, Critical Path: 0.39s
```

**Comment by damienmg** [comment]
https://travis-ci.org/google/bazel/jobs/68277285 travis did pass that steps (the build failed due to a known flakiness in the shell test).

**Comment by kchodorow** [comment]
Just reporting what I saw locally.  Maybe travis has an SDK installed that I don't.

**Comment by damienmg** [comment]
I did the test at the same CL and didn't got the issue. I guess it is coming from your ios SDK (do you have one installed? Xcode?)

stdredirect is a tool that was introduced recently. Before that there were no requirements of install dependency.

**Comment by kchodorow** [comment]
Nope, no xcode.  Pretty sure I don't have iOS SDK either, unless it comes with command line tools or something (which I doubt).

**Comment by damienmg** [comment]
I see. dmaclach introduced that change. TL;DR: stdredirect should be only built when xcrun is present and should warning if not...

**Comment by kchodorow** [comment]
This still gives a big ugly error in OS X.

**Comment by ekuefler** [comment]
Not only is it ugly, I think this bug is preventing fresh Bazel installs on OS X. The error aborts the compile script before it can set up the base workspace, so I wasn't able to get things running on a fresh machine without modifying compile.sh to skip the "Build tools" step.

**Comment by damienmg** [comment]
dmaclach: do you have ETA on this bug?

**Comment by ekuefler** [comment]
I did some more fiddling and realized that I also didn't have xcode installed, after installing it everything works. So it looks like the real issue here is that bazel requires xcode to be installed to build successfully on mac.
