### ISSUE TITLE
fedora 21 compile failure

### ISSUE THREAD

**Issue by hanwen** [google/bazel#263]
$ sh compile.sh 
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    compile.sh build /path/to/bazel
🍃  Building Bazel from scratch...........
🍃  Building Bazel with Bazel.
.Extracting Bazel installation...
.........
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'PACKAGE:src/main/java' (requested by nodes 'TARGET_MARKER://src/main/java:bazel-main_deploy.jar')
INFO: Elapsed time: 1.126s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:src/main/java' (requested by nodes 'TARGET_MARKER://src/main/java:bazel-main_deploy.jar')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:747)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$1.run(AbstractQueueVisitor.java:346)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: /home/hanwen/vc/bazel/src/main/java/BUILD:365:1: java.lang.NullPointerException (null)
while calling java_library(**kwargs) with args [{visibility=[//src/java_tools/buildjar:__pkg__], name=java-toolchain-parser, srcs=[com/google/devtools/build/lib/rules/java/JavaToolchainData.java, com/google/devtools/build/lib/rules/java/JavaToolchainDataParser.java, com/google/devtools/build/lib/concurrent/AbstractQueueVisitor.java, com/google/devtools/build/lib/concurrent/BatchedKeyedLocker.java, com/google/devtools/build/lib/concurrent/ExecutorUtil.java, com/google/devtools/build/lib/concurrent/KeyedFrequencyStore.java, com/google/devtools/build/lib/concurrent/KeyedLocker.java, com/google/devtools/build/lib/concurrent/MoreFutures.java, com/google/devtools/build/lib/concurrent/RefCountedHashMapKeyedFrequencyStore.java, com/google/devtools/build/lib/concurrent/RefCountedMultisetKeyedLocker.java, com/google/devtools/build/lib/concurrent/Sharder.java, com/google/devtools/build/lib/concurrent/ThreadSafety.java, com/google/devtools/build/lib/concurrent/ThrowableRecordingRunnableWrapper.java], deps=[:common, //src/main/protobuf:proto_build, //third_party:guava, //third_party:jsr305, //third_party:protobuf], testonly=1}, java_library(name = "java-toolchain-parser", testonly = 1, srcs = glob(["com/google/devtools/build/lib/rules/java/JavaToolchainData.java", "com/google/devtools/build/lib/rules/java/JavaToolchainDataParser.java", "com/google/devtools/build/lib/concurrent/*.java"]), visibility = ["//src/java_tools/buildjar:__pkg__"], deps = [":common", "//src/main/protobuf:proto_build", "//third_party:guava", "//third_party:jsr305", "//third_party:protobuf"]), Environment{$android_aapt_base -> $android_aapt_base(**kwargs), $android_base -> $android_base(**kwargs), $android_binary_base -> $android_binary_base(**kwargs), $android_binary_only -> $android_binary_only(**kwargs), $android_library_base -> $android_library_base(**kwargs), $android_resource_support -> $android_resource_support(**kwargs), $base_java_binary -> $base_java_binary(**kwargs), $base_py -> $base_py(**kwargs), $base_py_binary -> $base_py_binary(**kwargs), $base_rule -> $base_rule(**kwargs), $binary_base_rule -> $binary_base_rule(**kwargs), $cc_base_rule -> $cc_base_rule(**kwargs), $cc_binary_base -> $cc_binary_base(**kwargs), $cc_decl_rule -> $cc_decl_rule(**kwargs), $cc_library -> $cc_library(**kwargs), $cc_linking_rule -> $cc_linking_rule(**kwargs), $cc_rule -> $cc_rule(**kwargs), $config_base_rule -> $config_base_rule(**kwargs), $error_rule -> $error_rule(**kwargs), $ijar_base_rule -> $ijar_base_rule(**kwargs), $ios_test_base_rule -> $ios_test_base_rule(**kwargs), $j2objc_library_base -> $j2objc_library_base(**kwargs), $jack_mixin -> $jack_mixin(**kwargs), $java_base_rule -> $java_base_rule(**kwargs), $java_import_base -> $java_import_base(**kwargs), $java_rule -> $java_rule(**kwargs), $objc_alwayslink_rule -> $objc_alwayslink_rule(**kwargs), $objc_bundling_rule -> $objc_bundling_rule(**kwargs), $objc_compile_dependency_rule -> $objc_compile_dependency_rule(**kwargs), $objc_compiling_rule -> $objc_compiling_rule(**kwargs), $objc_linking_rule -> $objc_linking_rule(**kwargs), $objc_options_rule -> $objc_options_rule(**kwargs), $objc_opts_rule -> $objc_opts_rule(**kwargs), $objc_proto_rule -> $objc_proto_rule(**kwargs), $objc_release_bundling_rule -> $objc_release_bundling_rule(**kwargs), $objc_resource_tools_rule -> $objc_resource_tools_rule(**kwargs), $objc_resources_rule -> $objc_resources_rule(**kwargs), $objc_sdk_frameworks_depender_rule -> $objc_sdk_frameworks_depender_rule(**kwargs), $objc_simulator_rule -> $objc_simulator_rule(**kwargs), $objc_xcodegen_rule -> $objc_xcodegen_rule(**kwargs), $pkg_context -> com.google.devtools.build.lib.packages.PackageFactory$PackageContext@f6a5c5b, $rule -> $rule(**kwargs), $sh_target -> $sh_target(**kwargs), $test_base_rule -> $test_base_rule(**kwargs), $workspace_base_rule -> $workspace_base_rule(**kwargs), PACKAGE_NAME -> src/main/java, action_listener -> action_listener(**kwargs), android_binary -> android_binary(**kwargs), android_library -> android_library(**kwargs), android_ndk_repository -> android_ndk_repository(**kwargs), android_sdk -> android_sdk(**kwargs), android_sdk_repository -> android_sdk_repository(**kwargs), android_tools_defaults_jar -> android_tools_defaults_jar(**kwargs), bind -> bind(**kwargs), cc_binary -> cc_binary(**kwargs), cc_library -> cc_library(**kwargs), cc_test -> cc_test(**kwargs), cc_toolchain -> cc_toolchain(**kwargs), cc_toolchain_suite -> cc_toolchain_suite(**kwargs), config_setting -> config_setting(**kwargs), distribs -> distribs(distribution_strings), environment -> environment(**kwargs), environment_group -> environment_group(*, name: string, environments: list, defaults: list), experimental_ios_test -> experimental_ios_test(**kwargs), exports_files -> exports_files(srcs: list of strings, visibility: list or NoneType = None, licenses: list of strings or NoneType = None), extra_action -> extra_action(**kwargs), filegroup -> filegroup(**kwargs), genquery -> genquery(**kwargs), genrule -> genrule(**kwargs), glob -> glob(include: list of strings, exclude: list of strings = [], exclude_directories: int = 1), http_archive -> http_archive(**kwargs), http_jar -> http_jar(**kwargs), ios_application -> ios_application(**kwargs), ios_device -> ios_device(**kwargs), ios_extension -> ios_extension(**kwargs), ios_extension_binary -> ios_extension_binary(**kwargs), ios_test -> ios_test(**kwargs), j2objc_library -> j2objc_library(**kwargs), java_binary -> java_binary(**kwargs), java_import -> java_import(**kwargs), java_library -> java_library(**kwargs), java_plugin -> java_plugin(**kwargs), java_test -> java_test(**kwargs), java_toolchain -> java_toolchain(**kwargs), licenses -> licenses(license_strings: list of strings), local_repository -> local_repository(**kwargs), maven_jar -> maven_jar(**kwargs), mocksubinclude -> mocksubinclude(label, path: string), new_http_archive -> new_http_archive(**kwargs), new_local_repository -> new_local_repository(**kwargs), objc_binary -> objc_binary(**kwargs), objc_bundle -> objc_bundle(**kwargs), objc_bundle_library -> objc_bundle_library(**kwargs), objc_framework -> objc_framework(**kwargs), objc_import -> objc_import(**kwargs), objc_library -> objc_library(**kwargs), objc_options -> objc_options(**kwargs), objc_proto_library -> objc_proto_library(**kwargs), objc_xcodeproj -> objc_xcodeproj(**kwargs), package -> package(*, default_deprecation = ?, distribs = ?, licenses = ?, default_testonly = ?, default_visibility = ?, features = ?, default_compatible_with = ?, default_restricted_to = ?), package_group -> package_group(*, name: string, packages: list of strings = [], includes: list = []), py_binary -> py_binary(**kwargs), py_library -> py_library(**kwargs), py_test -> py_test(**kwargs), sh_binary -> sh_binary(**kwargs), sh_library -> sh_library(**kwargs), sh_test -> sh_test(**kwargs), test_suite -> test_suite(**kwargs), }=>Environment{- -> -(num: int), False -> false, None -> None, True -> true, bool -> bool(x), int -> int(x), len -> len(x), repr -> repr(x), select -> select(x: dict), sorted -> sorted(self: list), str -> str(x), }]
Java parameter types: [interface java.util.Map, class com.google.devtools.build.lib.syntax.FuncallExpression, class com.google.devtools.build.lib.syntax.Environment]
Skylark type checks: null
	at com.google.devtools.build.lib.syntax.BuiltinFunction.badCallException(BuiltinFunction.java:189)
	at com.google.devtools.build.lib.syntax.BuiltinFunction.call(BuiltinFunction.java:164)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:423)
	at com.google.devtools.build.lib.syntax.FuncallExpression.eval(FuncallExpression.java:533)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.exec(ExpressionStatement.java:39)
	at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:137)
	at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1282)
	at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromPreprocessingResult(PackageFactory.java:1011)
	at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:732)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:466)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:711)
	... 4 more
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.packages.Package$Builder.checkForConflicts(Package.java:1391)
	at com.google.devtools.build.lib.packages.Package$Builder.addRule(Package.java:1229)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:140)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:148)
	at com.google.devtools.build.lib.packages.PackageFactory.addRule(PackageFactory.java:904)
	at com.google.devtools.build.lib.packages.PackageFactory.access$900(PackageFactory.java:78)
	at com.google.devtools.build.lib.packages.PackageFactory$9.invoke(PackageFactory.java:942)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.devtools.build.lib.syntax.BuiltinFunction.call(BuiltinFunction.java:150)
	... 13 more

**Comment by damienmg** [comment]
Do you have a tools/build_rules/prelude_bazel?

What is the commit hash?

**Comment by hanwen** [comment]
curious, now it worked correctly, at 9fc1ce60f285e303058c40d1331712bd01067955
