### ISSUE TITLE
All builds failing with "no such package 'src/tools/android/[...]'"

### ISSUE THREAD

**Issue by ekuefler** [google/bazel#267]
Probably related to #249 but causing more immediate problems. After syncing past the latest Android changes, trying to build anything in my repo fails with the following message:

```
ERROR: /Users/erik/github/bazel/base_workspace/tools/android/BUILD:15:1: no such package 'src/tools/android/java/com/google/devtools/build/android': BUILD file not found on package path and referenced by '//tools/android:aar_generator'.
```

A couple targets in `tools/android` appear to depend directly on targets under Bazel's `src` directory, and `src` isn't in `base_workspace`, so it doesn't seem like this could possibly work.

**Comment by lberki** [comment]
Ugh, that's plusungood. I'll add src/tools/android to base_workspace until we can automatically fetch it from somewhere.
