### ISSUE TITLE
Dead links on the FAQ page

### ISSUE THREAD

**Issue by tommadams** [google/bazel#27]
The following links from the page http://bazel.io/docs/FAQ.html all 404:

https://github.com/google/bazel/blob/master/base_workspace/examples/cpp/BUILD
https://github.com/google/bazel/blob/master/base_workspace/tools/build_rules/py_rules.bzl
https://github.com/google/bazel/tree/master/base_workspace/examples/py

**Comment by hanwen** [comment]
these should be fixed now.
