### ISSUE TITLE
ijar tests are broken

### ISSUE THREAD

**Issue by lberki** [google/bazel#273]
Some tests require Java 8 lambdas to compile, and tools/jdk:toolchain has -source=7 -target=7 set. Thus, //src/ijar/test/... does not compile.

**Comment by damienmg** [comment]
Some tests requires a JDK8 in the environment, correct your JAVA_HOME. They explicitely set the good source and target.

This is documented in the developer documentation.

**Comment by damienmg** [comment]
WAI
