### ISSUE TITLE
Improve / clarify output when fetching a new_http_archive

### ISSUE THREAD

**Issue by mbeards** [google/bazel#283]
When building / running a target that depends on a new_http_archive, the only message printed during download is "INFO: Loading package:".

It'd be nice to have a progress bar, or at least some sort of spinner to know that it's alive / working.

**Comment by laszlocsomor** [comment]
Kristina, could you please take a look?

**Comment by damienmg** [comment]
I think this was resolved by
https://github.com/google/bazel/commit/1b9123646e21b05ed1ff8706f4b0f32c7d2efd60.
Michael, can you test with the latest version?
