### ISSUE TITLE
Workspace status command seems to persist even across clean build

### ISSUE THREAD

**Issue by damienmg** [google/bazel#284]
Assigning to Lukacs who might understand what's happening.

Context: on a mac, with change https://bazel-review.googlesource.com/#/c/1550/ patched in
TL;DR: If the status command is invalid, I have to do a `bazel clean --expunge` to make it work again:

    dmarting-macbookair:bazel-review dmarting$ ./output/bazel build examples/py:bin
    INFO: Found 1 target...
    ERROR: Process exited with status 127.
    Target //examples/py:bin failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 0.231s, Critical Path: 0.02s
    dmarting-macbookair:bazel-review dmarting$ ./output/bazel clean
    INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
    dmarting-macbookair:bazel-review dmarting$ ./output/bazel build examples/py:bin
    INFO: Found 1 target...
    ERROR: Process exited with status 127.
    Target //examples/py:bin failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 0.795s, Critical Path: 0.01s
    dmarting-macbookair:bazel-review dmarting$ ./output/bazel build --workspace_status_command=/usr/bin/true examples/py:bin
    INFO: Found 1 target...
    ERROR: Process exited with status 127.
    Target //examples/py:bin failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 0.090s, Critical Path: 0.01s
    dmarting-macbookair:bazel-review dmarting$ ./output/bazel clean
    INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
    dmarting-macbookair:bazel-review dmarting$ ./output/bazel clean --expunge
    INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
    dmarting-macbookair:bazel-review dmarting$ ./output/bazel build --workspace_status_command=/usr/bin/true examples/py:bin
    ........
    INFO: Found 1 target...
    Target //examples/py:bin up-to-date:
      bazel-bin/examples/py/bin.zip
      bazel-bin/examples/py/bin
    INFO: Elapsed time: 1.801s, Critical Path: 0.09s
    dmarting-macbookair:bazel-review dmarting$ ./output/bazel clean --expunge
    INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
    dmarting-macbookair:bazel-review dmarting$ ./output/bazel build --workspace_status_command=does.not.exists examples/py:bin
    .........
    INFO: Found 1 target...
    ERROR: Process exited with status 127.
    Target //examples/py:bin failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 1.942s, Critical Path: 0.05s
    dmarting-macbookair:bazel-review dmarting$ ./output/bazel build examples/py:bin
    INFO: Found 1 target...
    ERROR: Process exited with status 127.
    Target //examples/py:bin failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 0.192s, Critical Path: 0.01s
    dmarting-macbookair:bazel-review dmarting$ ./output/bazel clean --expunge
    INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
    dmarting-macbookair:bazel-review dmarting$ ./output/bazel build examples/py:bin
    .........
    INFO: Found 1 target...
    Target //examples/py:bin up-to-date:
      bazel-bin/examples/py/bin.zip
      bazel-bin/examples/py/bin
    INFO: Elapsed time: 2.029s, Critical Path: 0.12s

**Comment by lberki** [comment]
Well, a clue, I don't have, so let me just break out my debugging skills.
