### ISSUE TITLE
Action conflicts are possible with remote repositories

### ISSUE THREAD

**Issue by lberki** [google/bazel#293]
The artifacts of two rules with the same label but in a different repository have the same exec path. Thus, if you want to build something that has two such rules in its transitive closure, fail.

A minimal reproduction (takes a few files):

```
cat >> WORKSPACE <EOF
local_repository(name="br", path="/tmp/br")
bind(name="b", actual="@br//a:a")
EOF

mkdir -p a
cat > a/BUILD <<EOF
genrule(name="a", srcs=[], outs=["a.out"], cmd="echo MA > $@")
genrule(name="f", srcs=[":a", "//external:b"], outs=["f.out"], cmd = "cat $(SRCS) > $@")
EOF

mkdir -p /tmp/br/a
touch /tmp/br/WORKSPACE
cat > /tmp/br/a/BUILD <<EOF
genrule(name="a", srcs=[], outs=["a.out"], cmd="echo MB > $@", visibility=["//visibility:public"])
EOF
```

Then, `bazel build //a:f` fails with an action conflict. If "MB" is replace with "MA", the two actions are the same, thus, the build works as expected.

**Comment by lberki** [comment]
This is kinda important, because I expect that we hit this with the Android tools repository, since e.g. Guava will be both in the main repository and the Android tools one.

Thus, it may be better if I fix this; after all, I am the one who is motivated to do so.

**Comment by kchodorow** [comment]
Yeah, I've run into this, too.  It would be great to fix, feel free!

**Comment by lberki** [comment]
Problem is, it's not very simple. I'm thinking about prefixing the exec paths and the runfiles paths with the repository name specified in the WORKSPACE file, but it requires some thinking to get it right.

**Comment by lberki** [comment]
Here is a doc I've just written up on the solution I have in mine:

https://docs.google.com/document/d/1oHVRVUbHYczT9XNND8nYtmJNzvR4w6rsWzAfleqg47c/edit?usp=sharing
