### ISSUE TITLE
Name conflict precludes using android_ndk_repository on OS X

### ISSUE THREAD

**Issue by mrdomino** [google/bazel#297]
OS X likes its filesystems case-insensitive. The android NDK contains a top-level directory named "build". The android_ndk_repository rule attempts to create a file named "BUILD" at the top level. These conflict.

**Comment by lberki** [comment]
Wow, that's one unexpected complication. We'll probably move every file in the NDK to a subdirectory (note that we are all on a conference this week, so it may take a while)

**Comment by mrdomino** [comment]
I recommend superglue in order to keep your palm attached to your face without long-term fatigue.

Thanks for keeping me posted, and for all the work on the Android support. As a Xoogler currently working on a C++/Objective-C/Android project, I'm really excited about this.

**Comment by lberki** [comment]
Document describing the solution I have in mind:

https://docs.google.com/document/d/1oHVRVUbHYczT9XNND8nYtmJNzvR4w6rsWzAfleqg47c/edit?usp=sharing

**Comment by lberki** [comment]
FYI: This seems to be fixed. However, note that my personal main development platform is Linux and we have just enough problems with it, so building Android apps on OS X may or may not work at the moment. It would be awesome if you could give it a spin and report back! :)

**Comment by mrdomino** [comment]
The android_ndk_repository rule appears to work without error. Is there an Android example project anywhere yet?

**Comment by lberki** [comment]
I have one out for code review. Should hit the repository in a day or two. In the meantime, I'll send a .tar.gz over e-mail.
