### ISSUE TITLE
ZipTests is failing for me with "java.io.IOException: No space left on device"

### ISSUE THREAD

**Issue by janakdr** [google/bazel#299]
I don't have much disk space on my Macbook Air, but I do have 8 GB or so. I think maybe the test is using an in-memory filesystem and I'm low on swap? But it fails consistently.

**Comment by damienmg** [comment]
Normal these tests requires several gigabytes of memories to run. This is
working as intended.
Run with --test_tag_filter=-zip to skip them.

**Comment by damienmg** [comment]
btw you are missing free disk space I believe, not RAM. It creates multiple 4Gb files for tests on large zip files.
