### ISSUE TITLE
bazel build //examples/objc:PrenotCalculator fails unless ibtoolwrapper and realpath are executable

### ISSUE THREAD

**Issue by mrdomino** [google/bazel#300]
This is on a default workspace, with `build --ios_sdk_version=8.4` in my tools/bazel.rc. My generated tools/objc/ibtoolwrapper and tools/objc/realpath are not executable. Making them executable causes compilation to succeed, but I'm not sure if this is the correct solution, given that these files are generated in my workspace and not any of the bazel-* directories.

**Comment by dmaclach** [comment]
In progress. Sorry about that. For right now using chmod 755 on tools/objc/realpath and tools/objc/ibtoolwrapper is fine.

**Comment by mrdomino** [comment]
b8d1e700 appears to have introduced a new ibtoolwrapper fail. The example currently doesn't build on master anymore, although it did for a while after that commit.

**Comment by mrdomino** [comment]
Nvm, erroneous output from a hasty bisect. Fix incoming. This appears to have just been minor fallout from a rollback on Monday.

**Comment by mrdomino** [comment]
For reference, the fix is here: https://bazel-review.googlesource.com/#/c/1790/

Closing this issue as it appears to be unrelated.
