### ISSUE TITLE
Accept .c++ as an extension for cc_library / cc_binary srcs

### ISSUE THREAD

**Issue by kamalmarhubi** [google/bazel#302]
I'm attempting to port a project that uses .c++ as its extension to build with Bazel. This is not included in the [`ALLOWED_SRC_FILES`][allowed-src-files] set. I couldn't find the `CppFileTypes` source that the constants come from, so don't know where to change it even for local testing of the build.

[allowed-src-files]: https://github.com/google/bazel/blob/0c14ad1848d07c49fa2a95e8443ca2e8135aeb30/src/main/java/com/google/devtools/build/lib/bazel/rules/cpp/BazelCppRuleClasses.java#L77

**Comment by haxorz** [comment]
Without answering your actual question (sorry, I don't work on this part of Bazel so I don't know what, if any, policy issues there are here*)...

> I couldn't find the CppFileTypes source

I was also unable to find it via github search. Weird. Anyway, here it is:

https://github.com/google/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java

*That being said, I can't think of a good reason why we wouldn't want to allow this. E.g. 'srcs = ['foo.c++'] is completely legit from a syntax perspective (see http://bazel.io/docs/build-ref.html#lexi).

**Comment by davidzchen** [comment]
While this is a less-common file extension for C++ source files, it is used by a few projects, such as Capn Proto: https://github.com/sandstorm-io/capnproto/tree/master/c%2B%2B/src/capnp

**Comment by kamalmarhubi** [comment]
@haxorz thanks for the link to that bit of the source!

@davidzchen yeah, Cap'n Proto is the one I was looking to port :-)

**Comment by damienmg** [comment]
This is solved by 77ac48e2d0874d152c29b597113053f2629b3bc3
