### ISSUE TITLE
Test //src/test/shell/bazel:external_integration_test fails reprodicibly on my mac

### ISSUE THREAD

**Issue by damienmg** [google/bazel#305]
Under OS X 10.10 with commit ecd4ec4

The interesting part of the log:

    ** test_http_archive_tgz *******************************************************
    INFO: Reading 'startup' options from /private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/_tmp/external_integration_test_1/bazelrc: --output_user_root=/private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/_tmp/external_integration_test_1/root --host_javabase=/private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/bazel-out/local_darwin-dbg/bin/src/test/shell/bazel/external_integration_test.runfiles/external/local-jdk
    INFO: $TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/_tmp/external_integration_test_1'.
    ____Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
    10240+0 records in
    10240+0 records out
    10485760 bytes transferred in 0.030759 secs (340902126 bytes/sec)
    Expected build/run to succeed
    GET /fox.tar.gz HTTP/1.1
    User-Agent: Java/1.8.0_20
    Host: localhost:59511
    Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
    Connection: keep-alive
    
    src/test/shell/bazel/external_integration_test: line 107: 47492 Terminated: 15          nc_l $nc_port < $http_response >&$nc_log  (wd: /private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/_tmp/external_integration_test_1/repo2)
    -- Actual output: ------------------------------------------------------
    INFO: Reading 'startup' options from /private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/_tmp/external_integration_test_1/bazelrc: --output_user_root=/private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/_tmp/external_integration_test_1/root --host_javabase=/private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/bazel-out/local_darwin-dbg/bin/src/test/shell/bazel/external_integration_test.runfiles/external/local-jdk
    INFO: $TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/_tmp/external_integration_test_1'.
    ........
    ____Loading package: zoo
    ERROR: /private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/_tmp/external_integration_test_1/workspace/zoo/BUILD:1:1: no such package '@endangered//fox': Error reading tar file (unknown file type x for file PaxHeader/WORKSPACE) and referenced by '//zoo:breeding-program'.
    ERROR: Loading failed; build aborted.
    ____Elapsed time: 0.348s
    ERROR: Build failed. Not running target.
    ------------------------------------------------------------------------
    test_http_archive_tgz FAILED: Expected regexp Fraka-kaka-kaka-kaka-kow not found.
    src/test/shell/bazel/external_integration_test:195: in call to expect_log
    src/test/shell/bazel/external_integration_test:203: in call to http_archive_helper
    Cleaning up workspace
    INFO: Reading 'startup' options from /private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/_tmp/external_integration_test_1/bazelrc: --output_user_root=/private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/_tmp/external_integration_test_1/root --host_javabase=/private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/bazel-out/local_darwin-dbg/bin/src/test/shell/bazel/external_integration_test.runfiles/external/local-jdk
    INFO: $TEST_TMPDIR defined: output root default is '/private/var/tmp/_bazel_dmarting/a39677c474b0553e9a2a1767924a8dd2/bazel-review/_tmp/external_integration_test_1'.
    ____Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
    FAILED: test_http_archive_tgz

**Comment by kchodorow** [comment]
I'm not able to reproduce (I'm using 10.10.4, you must be a different version of tar or something), could you send me the .tar.gz file from your system?

**Comment by kchodorow** [comment]
Another user report: https://groups.google.com/d/msgid/bazel-discuss/cce5ae8b-f9cb-4784-9ad6-f673ede6a9a7%40googlegroups.com?utm_medium=email&utm_source=footer
