### ISSUE TITLE
`order` parameter of `set` global SkyLark function is not clearly documented

### ISSUE THREAD

**Issue by kamalmarhubi** [google/bazel#318]
http://bazel.io/docs/skylark/library.html#modules._top_level.set

The possible values are listed, but it's unclear when I'd want to use each.

**Comment by fweikert** [comment]
Thanks for bringing this to our attention! For now, the possible values are explained in the following files:

[Compile order](https://github.com/google/bazel/blob/master/src/main/java/com/google/devtools/build/lib/collect/nestedset/CompileOrderExpander.java#L19)
[Link order](https://github.com/google/bazel/blob/master/src/main/java/com/google/devtools/build/lib/collect/nestedset/LinkOrderExpander.java#L20)
[Naive link order](https://github.com/google/bazel/blob/master/src/main/java/com/google/devtools/build/lib/collect/nestedset/NaiveLinkOrderExpander.java#L19)

**Comment by kamalmarhubi** [comment]
@fweikert thanks for the links!

**Comment by fweikert** [comment]
I have updated the documentation on set: http://bazel.io/docs/skylark/library.html#modules.set

**Comment by kamalmarhubi** [comment]
Oh excellent, thanks!
