### ISSUE TITLE
Compiling Bazel fails if "zip" is not installed

### ISSUE THREAD

**Issue by carl-mastrangelo** [google/bazel#319]
Following the build instructions here: http://bazel.io/docs/getting-started.html

Compiling fails silently if the "zip" program is not installed  The culprit looks like scripts/bootstrap/compile.sh   Sample terminal interaction:

$ ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch...........scripts/bootstrap/compile.sh: line 305: zip: command not found

Creating Bazel self-extracting archive...
/tmp/bazel$ echo $?
1

The "Creating Bazel self-extracting archive..." should probably not be printed based on the previous error.

**Comment by damienmg** [comment]
I am unsure there is something to do here. The script fails with "zip: command not found".

**Comment by kchodorow** [comment]
I think the output is a little suboptimal, it would be clearer for the error to be at the end:

```
🍃 Building Bazel from scratch...........

Creating Bazel self-extracting archive...
scripts/bootstrap/compile.sh: line 305: zip: command not found
$
```

**Comment by damienmg** [comment]
we could wrap the zip command inside a run_silent. let me try that
