### ISSUE TITLE
compilation issue on Centos 6.6

### ISSUE THREAD

**Issue by bw-theo-omtzigt** [google/bazel#321]
Trying to bootstrap Bazel on a Centos 6.6 Vagrant machine and running into this compilation error:

INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch.....
Compiling client .cc files...
g++ -I. -std=c++0x -c -DBLAZE_JAVA_CPU="k8" -DBLAZE_OPENSOURCE=1 -o /tmp/bazel.pxM7U3YQ/objs/blaze_util.cc.o src/main/cpp/blaze_util.cc
src/main/cpp/blaze_util.cc: In function ‘bool blaze::IsStandardTerminal()’:
src/main/cpp/blaze_util.cc:219: error: ‘nullptr’ was not declared in this scope
src/main/cpp/blaze_util.cc: In function ‘void blaze::ExecuteProgram(const std::string&, const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)’:
src/main/cpp/blaze_util.cc:252: error: expected initializer before ‘:’ token
src/main/cpp/blaze_util.cc:258: error: expected ‘)’ before ‘;’ token
src/main/cpp/blaze_util.cc:261: error: ‘cwd’ was not declared in this scope

Has anyone successfully built Bazel on Centos 6.6?

**Comment by kchodorow** [comment]
It looks like we're using C++11 features but only requesting c++0x.  Can you change https://github.com/google/bazel/blob/master/scripts/bootstrap/compile.sh#L61 to `CXXSTD="c++11"` and try re-running?

**Comment by sdwilsh** [comment]
I found the version of g++ I had on Centos was way too old and didn't have `nullptr` (added in GCC 4.6 https://gcc.gnu.org/gcc-4.6/changes.html)
