### ISSUE TITLE
Unclear what the workflow is to create a base_workspace

### ISSUE THREAD

**Issue by bw-theo-omtzigt** [google/bazel#325]
The compile.sh script has an argument called 'init' that builds a base_workspace that contains symlinks to the essential infrastructure components of the bazel tree. The location of the base_workspace root directory is hardcoded to go under the bazel root directory.

If I have a project that exists in a separate tree, say ~/work/my-project, and that bazel is installed in, say /opt/bazel. What is the workflow to ordain my project at ~/work/my-project with the bazel symlinks?

**Comment by damienmg** [comment]
What do you mean? The install script should have setted-up to your ~/.bazelrc automatically so just doing "touch WORKSPACE" should be enough in your new directory, see http://bazel.io/blog/2015/04/06/Simplified-Workspace-Creation.html

**Comment by bw-theo-omtzigt** [comment]
Thanks for that link: due to an initial invokation that left the .bazelrc file inconsistent, the simple 'touch WORKSPACE' concept was not working. And the element that breaks is the symlink to '//tools' needed to pull in the python rule set. The link explains the goal and the ingredients, so a fresh install, build, and creation of the WORKSPACE file, confirmed your assertion that this should 'just' work. 

It would be great to have this tidbit of information (that the compile.sh sets up the .bazelrc so that you can make any directory a WORKSPACE and the bazel command knows how to find the proper dependent directories) in the "Getting Started" section. If stuff goes bad, there isn't enough information to troubleshoot what is not working.
