### ISSUE TITLE
77ab8ce766621782e4c4a3c71ac59df0f71fe310 introduced a dependency to xcode tooling in the test suite which fails to build on Linux

### ISSUE THREAD

**Issue by damienmg** [google/bazel#332]
Commit 77ab8ce766621782e4c4a3c71ac59df0f71fe310  add a Objc tests and it requires Xcode tooling which is not available on linux

    $ ./compile.sh test ./output/bazel
    🍃  Running tests.
    INFO: Found 40 test targets...
    INFO: From Executing genrule //src/tools/xcode/realpath:realpath_genrule:
    /bin/bash: /usr/bin/xcrun: No such file or directory
    ERROR: /tmp/bazel/src/tools/xcode/realpath/BUILD:4:1: Couldn't build file src/tools/xcode/realpath/realpath: Executing genrule //src/tools/xcode/realpath:realpath_genrule failed: bash failed: error executing command /bin/bash -c 'source tools/genrule/genrule-setup.sh; /usr/bin/xcrun clang -o bazel-out/local_linux-fastbuild/bin/src/tools/xcode/realpath/realpath src/tools/xcode/realpath/realpath.c': com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    INFO: From Executing genrule //src/tools/xcode/stdredirect:stdredirect_genrule:
    /bin/bash: /usr/bin/xcrun: No such file or directory
    /bin/bash: /usr/bin/xcrun: No such file or directory
    ERROR: /tmp/bazel/src/tools/xcode/stdredirect/BUILD:4:1: Couldn't build file src/tools/xcode/stdredirect/StdRedirect.dylib: Executing genrule //src/tools/xcode/stdredirect:stdredirect_genrule failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
    ^C
    Bazel caught interrupt signal; shutting down.

    ERROR: /tmp/bazel/src/test/shell/bazel/BUILD:77:1: Couldn't build file src/test/shell/bazel/doc-srcs.zip: Executing genrule //src/test/shell/bazel:doc-srcs failed: bash failed: error executing command /bin/bash bazel-out/local_linux-fastbuild/genfiles/src/test/shell/bazel/doc-srcs.genrule_script.sh: com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
    ERROR: /tmp/bazel/src/main/java/BUILD:180:1: Couldn't build file src/main/java/libanalysis-exec-rules-skyframe.jar: Java compilation in rule '//src/main/java:analysis-exec-rules-skyframe' failed: java failed: error executing command external/local-jdk/bin/java -Xbootclasspath/p:third_party/java/jdk/langtools/javac.jar -client -jar tools/jdk/JavaBuilder_deploy.jar ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
    ERROR: /tmp/bazel/src/main/java/BUILD:180:1: Couldn't build file src/main/java/libanalysis-exec-rules-skyframe.jar: Java compilation in rule '//src/main/java:analysis-exec-rules-skyframe' failed: java failed: error executing command external/local-jdk/bin/java -Xbootclasspath/p:third_party/java/jdk/langtools/javac.jar -client -jar tools/jdk/JavaBuilder_deploy.jar ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
    ERROR: build interrupted.
    INFO: Elapsed time: 1.716s, Critical Path: 1.54s

**Comment by SummerLife** [comment]
Hello,would you like to tell me the way to solve it? Thank you very much!
