### ISSUE TITLE
Cannot run example android binary

### ISSUE THREAD

**Issue by XperielIndigo** [google/bazel#334]
Hi everyone,

When I run `bazel mobile-install //examples/android/java/bazel:hello_world` I get an error: `bazel-out/host/bin/tools/android/stubify-manifest: line 3: python2: command not found`.

When I create a symlink `/usr/bin/python2 = /usr/bin/python` it works fine.

Is there another, less hacky, way to fix this?

Cheers
Indigo

**Comment by mrdomino** [comment]
I can confirm this on OS X. I have a python2 on my path, but it's at /opt/local/bin, which I guess is ignored somehow. Sticking python2 in /usr/bin fixes it for me too.

**Comment by damienmg** [comment]
Lukacs: is there a way to fix that python2 stuff definitely? Maybe with a shell wrapper?

**Comment by lberki** [comment]
We'll simply point to /usr/bin/python for the time being.

We have some scaffolding to select different Python binaries, but they are mostly for Google-internal use, because we don't have the infrastructure in Bazel to make use of it. Let me send out a quick change.

**Comment by lberki** [comment]
Sent out a change. It's a one-liner, so it should be in tomorrow's push. In the meantime, you can use the `--python2_path=python` command line option to make it work (what the change does is to make that command line option the default).

**Comment by XperielIndigo** [comment]
Great, thanks.

**Comment by lberki** [comment]
(Ping me if the workaround doesn't work or if you run into other problems!)
