### ISSUE TITLE
JNI libraries with dependencies are broken

### ISSUE THREAD

**Issue by mrdomino** [google/bazel#335]
On [mrdomino/bazel/android-lib-deps](https://github.com/mrdomino/bazel/tree/android-lib-deps), the example app installs successfully but dies with an UnsatisfiedLinkError when it is run, e.g.:

```
V/Bazel   (17203): Hello, Android
V/Bazel   (17203): Lib says: Hello Lib
D/dalvikvm(17203): Trying to load lib /data/data/bazel.android/lib/libjni_dep.so 0x42628768
D/dalvikvm(17203): Added shared lib /data/data/bazel.android/lib/libjni_dep.so 0x42628768
D/dalvikvm(17203): No JNI_OnLoad found in /data/data/bazel.android/lib/libjni_dep.so 0x42628768, skipping init
D/dalvikvm(17203): Trying to load lib /data/data/bazel.android/lib/libjni.so 0x42628768
E/dalvikvm(17203): dlopen("/data/data/bazel.android/lib/libjni.so") failed: dlopen failed: cannot locate symbol "_Z15NewStringLatin1P7_JNIEnvPKc" referenced by "libjni.so"...
D/AndroidRuntime(17203): Shutting down VM
W/dalvikvm(17203): threadid=1: thread exiting with uncaught exception (group=0x41d23c08)
E/AndroidRuntime(17203): FATAL EXCEPTION: main
E/AndroidRuntime(17203): Process: bazel.android, PID: 17203
E/AndroidRuntime(17203): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Z15NewStringLatin1P7_JNIEnvPKc" referenced by "libjni.so"...
E/AndroidRuntime(17203): 	at java.lang.Runtime.loadLibrary(Runtime.java:365)
E/AndroidRuntime(17203): 	at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime(17203): 	at bazel.MainActivity.onCreate(MainActivity.java:18)
E/AndroidRuntime(17203): 	at android.app.Activity.performCreate(Activity.java:5451)
E/AndroidRuntime(17203): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
E/AndroidRuntime(17203): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
E/AndroidRuntime(17203): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
E/AndroidRuntime(17203): 	at android.app.ActivityThread.access$900(ActivityThread.java:175)
E/AndroidRuntime(17203): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
E/AndroidRuntime(17203): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(17203): 	at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(17203): 	at android.app.ActivityThread.main(ActivityThread.java:5602)
E/AndroidRuntime(17203): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(17203): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(17203): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime(17203): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime(17203): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 2435):   Force finishing activity bazel.android/bazel.MainActivity
```

Note that in that stack trace, libjni_dep.so is loaded separately prior to loading libjni.so (i.e. it comes from the tip of the branch), but the same error occurs if libjni_dep.so is not explicitly loaded. As far as I can tell, all libraries are successfully compiled and copied to the device.

**Comment by lberki** [comment]
I can reproduce this. Investigating. I currently have no clue what goes wrong :( -- the libraries are on the device, libjni_dep.so defines the symbol `_Z15NewStringLatin1P7_JNIEnvPKc`  .

**Comment by lberki** [comment]
Actually, the same issue happens with vanilla Linux, too: apparently, the symbols of one dlopen()ed library are not accessible to other dlopen()ed libraries, at least not that easily. Digging further.

**Comment by lberki** [comment]
Hm, on my Ubuntu, LD_DEBUG says that the dynamic linker doesn't look for libjni_dep.so the symbol libjni.so requires. This seems to be similar to the problem with Android.

**Comment by mrdomino** [comment]
I did notice that -- readelf -d claims that the libraries bazel generates don't have any dependencies except on libc and libm. Initially this seemed heartening, as I took it to mean that bazel had made me a single library with all my dependencies wrapped up inside it.

**Comment by lberki** [comment]
Well, actually, Bazel *does* build a big single library with if you add the `legacy_native_support=0` to the `android_binary` rule. Well, except that I just tried that and it did not work:

https://github.com/google/bazel/issues/338

I'll try to get to the end of this tomorrow. The combination of these two is quite embarrassing.

**Comment by mrdomino** [comment]
Sounds good, thanks for the help. Glad this was at least easy to reproduce.

**Comment by lberki** [comment]
Issue found. I hope Ulf reviews it soon so that I can put this in today's push.

**Comment by lberki** [comment]
I'm not gonna make this today. Our internal test infrastructure is very, very, very convoluted :(

**Comment by mrdomino** [comment]
Aww, okay. Curious to see what it was in the end.

**Comment by lberki** [comment]
Hah. I got it right the last minute. I'm pushing it right after I send this
message :)

On Wed, Jul 29, 2015 at 5:50 PM, Steven Dee <notifications@github.com>
wrote:

> Aww, okay. Curious to see what it was in the end.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/bazel/issues/335#issuecomment-125996280>.
>



-- 
Lukács T. Berki | Software Engineer | lberki@google.com |

Google Germany GmbH | Dienerstrasse 12 | 80331 München | Germany |
Geschäftsführer:
Graham Law, Christine Elizabeth Flores | Registergericht und -nummer:
Hamburg, HRB 86891

**Comment by lberki** [comment]
...aaand, it's pushed:

https://github.com/google/bazel/commit/a93c63bb96ac9f540d8d39ae4158cc8bd335e127

Add the legacy_native_support=0 attribute to your rule, use
System.loadLibrary("hello_world"), and you should be good to go.

There is a somewhat embarrassing incrementality issue (
https://github.com/google/bazel/issues/344 ), but as long as you don't
change the value of --fat_apk_cpu, you should be fine, and since we
currently only support armeabi-v7a, there is not much reason to.

On Wed, Jul 29, 2015 at 5:52 PM, Lukács T. Berki <lberki@google.com> wrote:

> Hah. I got it right the last minute. I'm pushing it right after I send
> this message :)
>
> On Wed, Jul 29, 2015 at 5:50 PM, Steven Dee <notifications@github.com>
> wrote:
>
>> Aww, okay. Curious to see what it was in the end.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/google/bazel/issues/335#issuecomment-125996280>.
>>
>
>
>
> --
> Lukács T. Berki | Software Engineer | lberki@google.com |
>
> Google Germany GmbH | Dienerstrasse 12 | 80331 München | Germany | Geschäftsführer:
> Graham Law, Christine Elizabeth Flores | Registergericht und -nummer:
> Hamburg, HRB 86891
>
>


-- 
Lukács T. Berki | Software Engineer | lberki@google.com |

Google Germany GmbH | Dienerstrasse 12 | 80331 München | Germany |
Geschäftsführer:
Graham Law, Christine Elizabeth Flores | Registergericht und -nummer:
Hamburg, HRB 86891
