### ISSUE TITLE
Android binary JNI dependency name conflicts

### ISSUE THREAD

**Issue by XperielIndigo** [google/bazel#339]
Hi everyone,

I'm linking a cc_library tree to an android_binary and I'm running into a naming issue.

Apparently no cc_library can share the same local name (e.g. "common").

When I try to build my android_binary I get the follow error (example):

```
ERROR: /path/to/android/binary/BUILD:1:1: in android_binary rule //path/to/binary/binary:binary: Each library in the transitive closure must have a unique basename, but two libraries had the basename "libcommon.so": path/to/first/common/libcommon.so and path/to/second/common/libcommon.so
```

Is there anyway of getting around this without giving the path of the build in the basename?

Cheers
Indigo

**Comment by lberki** [comment]
That's complicated... basically, Android requires us to give a different name to every library, and that name is used in the System.loadLibrary() call, so it needs to be at least somewhat user-friendly (i.e. no checksum-based names or similar tricks)

The current solution is to just use the basename of each library, which can, of course, lead to conflicts. This is one of the reasons why legacy_support_0 was invented. It just links all the native code together in one big happy library.

**Comment by XperielIndigo** [comment]
Perfect, thanks Lukács.

**Comment by ldjhust** [comment]
@lberki @XperielIndigo Hi, what's the solution here? I have the same problem, but I don't get anything by search `legacy_support_0` in Bazel's doc.

Thank you very much!
