### ISSUE TITLE
Can [new_]http_archive support .tgz as well as .zip?

### ISSUE THREAD

**Issue by steven-johnson** [google/bazel#340]
new_http_archive seems like a convenient way to bring in prebuilt binary releases from non-Bazel projects (e.g., from a GitHub project's Releases archive), but .tgz seems to a common choice for Linux/OSX releases (e.g., https://github.com/halide/Halide/releases, which uses .tgz for Linux and OSX, and .zip only for Windows). Any chance we could get formats other than .zip supported as well?

**Comment by damienmg** [comment]
It does support .tar.gz and .tgz. It was just undocumented. The documentation has been updated and will be fixed on our next push to githb
