### ISSUE TITLE
Android Rule Documentation in Build Encyclopedia

### ISSUE THREAD

**Issue by davidzchen** [google/bazel#343]
Since Android rules are now available, let's add the documentation for the rules to the Build Encyclopedia.

**Comment by damienmg** [comment]
The documentation is there but they are marked as "undocumented" so it's just a matter of switching the flag for where it makes sense.

**Comment by lberki** [comment]
This has been fixed in e812e4136260fea8e3f10a5ecb759fdb401782ee (but forgot to annotate the commit with this bug)
