### ISSUE TITLE
//scripts/release:release_test is broken

### ISSUE THREAD

**Issue by lberki** [google/bazel#345]
Broken by https://github.com/google/bazel/commit/fa15d3983b4616516c350bb633335d2f27b9a674

I temporarily disabled the tests in https://github.com/google/bazel/commit/49543429f56cfe9c90562a1e9f9c66a9eabb5385

**Comment by damienmg** [comment]
fixed by 6ac7bd5f917e2d32705e5990f31b015db6a251f2
