### ISSUE TITLE
Linking against libm methods broken on Linux

### ISSUE THREAD

**Issue by mrdomino** [google/bazel#353]
[mrdomino/cos-bug](https://github.com/mrdomino/bazel/tree/cos-bug) is a minimal example of this. Here's what happens when I try to compile it on my Ubuntu 15.04 VM:

```
$ bazel build //examples/cpp:hello-world
INFO: Found 1 target...
INFO: From Linking examples/cpp/hello-world:
/usr/bin/ld: bazel-out/local_linux-fastbuild/bin/examples/cpp/_objs/hello-world/examples/cpp/hello-world.pic.o: undefined reference to symbol 'cos@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ERROR: /home/tux/bazel/examples/cpp/BUILD:9:1: Linking of rule '//examples/cpp:hello-world' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local_linux-fastbuild/bin/examples/cpp/hello-world bazel-out/local_linux-fastbuild/bin/examples/cpp/_objs/hello-world/examples/cpp/hello-world.pic.o ... (remaining 10 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
```

I don't have a 14.04 VM around to test on, but I've seen this behaviour manifest across diverse Linux environments.

**Comment by damienmg** [comment]
Assigning to Ulf for giving insights.

**Comment by mrdomino** [comment]
This seems like somewhat of a big deal since most non-trivial projects pull in libm somehow.

**Comment by mrdomino** [comment]
This is blocking one of our teams. Updates, background info, and workarounds greatly appreciated.

I suppose we could somehow pull libm into the bazel tree?

**Comment by mrdomino** [comment]
FYI, I've also confirmed this on Ubuntu 14.04.

**Comment by mrdomino** [comment]
Adding -lm to linkopts fixes this.

In related news would somebody be interested in taking this idiot ball off my hands?
