### ISSUE TITLE
How to inherit 'defines' from other targets?

### ISSUE THREAD

**Issue by brooksbp** [google/bazel#363]
I'd like to do the following:

```
cc_library(
  name = "libA",
  srcs = ["libA.cc"],
  defines = ["MY_DEFINE"],
)

cc_binary(
  name = "binX",
  srcs = ["binX.cc"],
  deps = [":libA"],  # This will inherit libA's defines such that binX is compiled with -DMY_DEFINE
)
```

Is this possible?

**Comment by damienmg** [comment]
I don't think it is possible but hanwen has more insight than me on the C++ rules

**Comment by hanwen** [comment]
According to http://bazel.io/docs/build-encyclopedia.html#cc_library.defines , this is already the way it works. Please file a bug if it doesn't work as documented.
