### ISSUE TITLE
All builds failing on OS X after recent change

### ISSUE THREAD

**Issue by ekuefler** [google/bazel#364]
After updating Bazel, all my builds fail with "ERROR: No toolchain found for cpu 'armeabi-v7a'." The culprit seems to be a93c63bb96ac9f540d8d39ae4158cc8bd335e127; reverting it fixes the problem.

**Comment by dslomov** [comment]
Do you perchance override the default toolchain detection logic, e.g. by using --compiler option?

**Comment by ekuefler** [comment]
I don't think so. I had `--android_crosstool_top=@androidndk//:toolchain`, but it still fails even if I remove it. Even removing everything in my repo's .bzelrc and running with no command-line flags causes the error. Is there a flag I can pass that will dump out all of the flags bazel has decided to run with so I can double-check?

**Comment by ekuefler** [comment]
Poked at this a little, it's definitely NDK related. In the iteration at https://github.com/google/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CrosstoolConfigurationLoader.java#L334 it's looking for the "armeabi-v7a" CPU, but the only candidate is "arm". This suggests that it's coming from https://github.com/google/bazel/blob/a93c63bb96ac9f540d8d39ae4158cc8bd335e127/src/main/java/com/google/devtools/build/lib/bazel/rules/android/AndroidNdkRepositoryFunction.java#L72, which has a bunch of TODOs. In particular it seems like https://github.com/google/bazel/commit/a93c63bb96ac9f540d8d39ae4158cc8bd335e127#diff-29700e31c4785eb8dd7e5f3164b3fea2R144 or the other change in that file is likely to be a problem - it's now definitely setting default_cpu to a value that doesn't appear in cpus. I don't know enough about what this code is doing to fix it though.

**Comment by damienmg** [comment]
Alex: can you comment on this one? Is the change you are preparing might
fix that?

**Comment by ahumesky** [comment]
I see, yes, andorid_default_fat_apk_cpus should probably have been arm. All of this should get fixed through in my change. It should be in early next week. In the meantime, I'll add armeabi-v7a to AndroidNdkRepositoryFunction and that should get people unstuck.

**Comment by ahumesky** [comment]
Hmm, I wasn't able to reproduce this on linux or os x with bazel at head and the example android app, which uses the NDK. Erik do you have steps to reproduce this?

**Comment by ekuefler** [comment]
Weird. In trying to isolate this it looks like the problem is caused by my `android_ndk_repository` in my WORSPACE. I've defined it like this near the top of WORKSPACE:

```
android_ndk_repository(
  name="androidndk",
  path="/usr/local/share/android-ndk",
  api_level=21)
```

And I'm pretty sure the path is valid:
```
$ ls /usr/local/share/android-ndk/platforms/
android-12 android-14 android-16 android-18 android-21 android-4  android-8
android-13 android-15 android-17 android-19 android-3  android-5  android-9
```

If I comment out the `android_ndk_repository` I can build things that don't depend on the NDK again. Not sure what's wrong with it though as it seems to match the sample.

**Comment by ahumesky** [comment]
So if I build this:
bazel build examples/android/java/bazel:hello_world --fat_apk_cpu=armeabi-v7a

it works, but if I do --fat_apk_cpu=arm, it fails with "ERROR: No toolchain found for cpu 'arm'.", so my original suggestion is not right.

Can you try a fresh bazel repo with the android example to see if you can get that to build at least?

**Comment by ekuefler** [comment]
I tried cloning and rebuilding a fresh bazel, copy/pasting my android_sdk_repository and android_ndk_repository rules from my WORKSPACE into the bazel workspace, building `examples/android/java/bazel:hello_world`, and it all seems to go fine and give me an APK. So it's not the repo definition itself that's the problem. I match what you're getting in that it passes with "--fat_apk_cpu=armeabi-v7a" and fails with "--fat_apk_cpu=arm"

However, if I go back to my original repo, the flags are reversed. Everything works again if I explicitly pass "--fat_apk_cpu=arm", and fails if I pass "--fat_apk_cpu=armeabi-v7a" (or nothing). So it seems like either my repo or the bazel repo must be configuring the default somehow.

**Comment by ekuefler** [comment]
I also tried copying the android samples to a new directory outside of bazel and making a new WORKSPACE with just the sdk and ndk, and that seemed to work too. So it must be something about my repository in particularly that's changing things. I can't recall ever changing anything like that though. Where might such a configuration exist?

**Comment by ahumesky** [comment]
If you haven't already tried it, one thing you can do is a "bazel clean" in your workspace that's not working. When the android_sdk_repository function first executes, it symlinks the android ndk into "bazel-<workspace name>/external/<android_sdk_repository rule name>/" as "ndk" and generates a workspace and a build file for it. When you updated bazel and tried to use the new one in your current workspace, it might not have regenerated the build and workspace files for the NDK, and the change you mentioned updates the templates used for those files.

**Comment by ekuefler** [comment]
After syncing to bazel head this morning the problem seems to have gone away, and I can't get it to repro even if I build at an old commit and the rebuild it at head. Maybe a recent commit like 8c2881324d2e98bbc876b84eddd58baa98d40121 resolved it? Thanks for your help.

**Comment by ahumesky** [comment]
Glad it's working for you now, even though we're not sure why it wasn't working. Regenerating everything with a new workspace might have cleared out some old / bad state (which would be a bug in bazel, doing clean shouldn't get things working). Commit 8c28813 is about getting bazel itself to run on arm, so that shouldn't have fixed this. A (regular) cpp toolchain was added in the crosstools, but if that one were getting picked up, it should still fail because all the tool entries point to /bin/false.
