### ISSUE TITLE
Appropriate way to handle out directories

### ISSUE THREAD

**Issue by pspeter3** [google/bazel#369]
Tools that have many to many commands, such as `tsc` and `scalac` often require an out directory as an argument. What is the correct way to model the out directory pattern in bazel? Generate a dummy file and grab the directory name?

**Comment by laszlocsomor** [comment]
Do you want to run the command in a `genrule` or something else?

**Comment by pspeter3** [comment]
I was running it with `ctx.action` but it is essentially a genrule in that I'm shelling out to another script.

**Comment by kchodorow** [comment]
Generally you create an archive from the output files (e.g., zip them up)
and use the archive as the output file.

**Comment by pspeter3** [comment]
Thanks for the suggestion. I'll investigate that option.
