### ISSUE TITLE
proc:only java_libraries fail with "Expected at least one FLOW event"

### ISSUE THREAD

**Issue by ekuefler** [google/bazel#379]
I have a java_library to which I pass `javacopts = ["-proc:only"]`. It recently started failing with the following message:

```
Expected at least one FLOW event
BazelJavaBuilder threw exception: java compilation returned status ABNORMAL
```

The culprit appears to be e927532a03addbcdd1e716b8453b53d9c3eb98e1. It fails at this commit and works at cd03ca2. It also works if I remove proc:only

**Comment by ahumesky** [comment]
Cushon, can you comment on this?
Do you have annotation processors for this java_library? Do these annotation processors generate code?

**Comment by ekuefler** [comment]
Yes, there are several processors running on the library, which generate both Java and C++ code. For this particular library I'm only interested in the C++ output so I can extract it with a genrule and dump into a cc_library, which is why I don't care about the java compilation and am trying to skip it with -proc:only.

**Comment by ahumesky** [comment]
Even with -proc:only working, you might run into trouble with the genrule, because the genrule must declare its outputs. If you know the names of the c++ files then you can do that (eg the annotation processors are only going to output 1 file each), but if the names of the c++ files are known only at runtime (eg they're based on java class names, fields, etc) then you won't know what to put in the genrule's outputs. The usual advice here is to have the genrule output a zip file, but cc_library isn't going to know what to do with a zip file. You might be able to do something in skylark to make this work, but I haven't tried it.

**Comment by ekuefler** [comment]
Yeah, I do have to explicitly list all the expected files, which fortunately I can figure out at compile time. It's a pain though, and I filed https://github.com/google/bazel/issues/317 a while back specifically for this use case.

This definitely was all working for me before e927532, it looks to me like the change was just too aggressive in assuming that successful builds would always have a FLOW event, when this isn't quite true in the case of proc:only. Technically everything works fine for me if I drop proc:only, it just means the build is doing a bit more work than it needs to.

**Comment by cushon** [comment]
I realized after pushing that change that it affects compilations with sources but no actual class declarations. That's case appears to be rare, and is generally an accident. I hadn't seen the `-proc:only` case yet. I'm planning to at least polish up the diagnostic introduced in e927532a03addbcdd1e716b8453b53d9c3eb98e1.

We can also relax the check, but I'm interested in your use case. If the same processor is responsible for the Java and c++ output, can you configure it to only output c++? If the output is from different processors, can you disable the Java one?

**Comment by ekuefler** [comment]
Here's my use case (digressing a fair bit from Bazel here):

The basic structure of what I'm writing is very similar to AutoValue (the two have kind of been converging in their feature sets from both directions over the past year), where I have an abstract class defining a value type for which an implementation and other supporting classes are generated. My system is more focused on extensibility and cross-language compilation than AutoValue is; users can write extensions which can cause other files (java sources, non-java sources, or arbitrary text files) to be generated by the annotation processor along with the core implementation classes. Examples are a Java JSON serializer for each value type or a direct C++ translation of each value type. The set of extensions to run is defined by passing a -A flag to javac. I hook it into Bazel by defining different targets that enable different extensions, which means other targets can depend on `:foo-base` to get just the core implementation, `:foo-json` to get the json serializers, and (through a layer of genrule ugliness) `:foo-cc` to get a C++ library.

Right now it always generates the core implementation even if it's only running C++ plugins, which it technically shouldn't need to. However, if I disable this, the compilation fails since the (user-defined) abstract class now can't find the (generated, like AutoValue's _Impl) implementation class. javac seems to want to compile the classes I pass it even with `-proc:only`. I'm not sure if there's a way to shut down all compilation attempts and run only the annotation processor in this case to get C++ output, but if there were I could probably do so.

So to directly answer your question, in the current implementation the core and plugin processor are two separate processors. I cannot disable the Java processor since it's required to compile the input classes (unless javac has a -nocompile flag of some sort that I missed).

**Comment by cushon** [comment]
Thanks for the background. I was missing that this affects all compilations with `-proc:only`, not just ones with no sources. I just mailed a fix that should make its way out to github in the next day or so.

> javac seems to want to compile the classes I pass it even with -proc:only. I'm not sure if there's a way to shut down all compilation attempts and run only the annotation processor in this case to get C++ output, but if there were I could probably do so.

I don't know of a way to do that, FWIW. `-proc:only` gets you part of the way there, since missing symbols inside a method body will be ignored. But if some class extends a missing symbol symbol (for example) the compilation will still fail.
