### ISSUE TITLE
Non-reproducible build after changing android installation

### ISSUE THREAD

**Issue by ekuefler** [google/bazel#380]
My android build failed because I didn't have the right SDK packages installed. After installing them, I had to run `bazel clean` for the changes to be picked up:

```
$ bazel build src/main/java/com/mycompany/android/...
ERROR: missing input file '@androidsdk//:build-tools/22.0.1/zipalign'.
$ echo y | /opt/android-sdk/tools/android update sdk -u -a -t android-21,build-tools-22.0.1
$ bazel build src/main/java/com/mycompany/android/...
ERROR: missing input file '@androidsdk//:build-tools/22.0.1/zipalign'.
$ bazel clean
$ bazel build src/main/java/com/mycompany/android/...
<success>
```

Cleaning is a trivial workaround, so this isn't a serious problem itself, but it might lead to more insidious reproducibility bugs.

**Comment by kchodorow** [comment]
This sounds like it's probably another instance of #352.
