### ISSUE TITLE
Error building on OS X relating to jdk/lib/missioncontrol/Java Mission Control.app/Contents/Info.plist

### ISSUE THREAD

**Issue by sarwarbhuiyan** [google/bazel#381]
Hello all,

I was building bazel successfully before but recently I'm getting the error below which suggests it does not like spaces in the name of this path to Mission Control on OS X. I'm not sure if I'm doing anything wrong but I have tried reinstalling the JDK, setting the JAVA_HOME variable, but to no avail. Is there something really basic I'm missing?

Sarwars-MacBook-Pro:bazel sarwar$ ./compile.sh
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh build /path/to/bazel
🍃  Building Bazel from scratch...........
🍃  Building Bazel with Bazel.
.Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=81997)... done.
.......
ERROR: /Users/sarwar/dev/bazel/tools/jdk/BUILD:93:1: //tools/jdk:package-srcs: invalid label 'jdk/lib/missioncontrol/Java Mission Control.app/Contents/Info.plist' in element 268 of attribute 'srcs' in 'filegroup' rule: invalid target name 'jdk/lib/missioncontrol/Java Mission Control.app/Contents/Info.plist': target names may not contain ' '.
ERROR: /Users/sarwar/dev/bazel/src/java_tools/buildjar/BUILD:225:1: every rule of type bootstrap_java_binary implicitly depends upon the target '//tools/jdk:jdk',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 0.973s

Building output/bazel

**Comment by damienmg** [comment]
There is an old symlink from a previous Bazel version that is not needed anymore, just remove it:
rm tools/jdk/jdk

**Comment by sarwarbhuiyan** [comment]
Thanks Damien!
