### ISSUE TITLE
Having src/... stuff in the base_workspace is problematic

### ISSUE THREAD

**Issue by damienmg** [google/bazel#384]
As per discussion with Lukacs, this should be fixed by having all android dependencies in remote repository. Creating that bug to track the issue.

More from IRC:
https://gist.github.com/damienmg/292f849e76dd9f2bcb83

Assigning to Lukacs for updating when this is fixed.

**Comment by talios** [comment]
+2 Cheers for the help in IRC regarding this. I was going a bit crazy. The reference in the discussion to `--deleted_packages=src/main/java` was key here. What I find interesting is that I got that same error earlier in the day but it didn't seem to consistently happen across clean+build runs.
