### ISSUE TITLE
Website seems to not support https

### ISSUE THREAD

**Issue by WYSIATI** [google/bazel#39]
Just tried
https://bazel.io/docs/getting-started.html  and
http://bazel.io/docs/getting-started.html.

I couldn't open https one.

**Comment by drmuzik** [comment]
Unfortunately, Github does not support https with custom URLs. https will work if you go directly to google.github.io/bazel/ but not bazel.io.

**Comment by WYSIATI** [comment]
@drmuzik The link worked but when I clicked, say, get started using Bazel to request a redirection, I got http 443 error. OS: Mac OS 10.10, Browser: Chrome Version 41.0.2272.104 (64-bit)

**Comment by drmuzik** [comment]
Ah, I see the issue. The links are referencing https://bazel.io/foo/bar even though you're viewing the index from google.github.io/bazel. I'll update this issue again when we get it fixed.

**Comment by damienmg** [comment]
The links have been fixed.
