### ISSUE TITLE
Default simulator architecture now x86_64 instead of standard i386

### ISSUE THREAD

**Issue by XperielIndigo** [google/bazel#398]
Hi,

I've tried running an iOS app I'm developing with `bazel run` and it now breaks as some libraries I depend don't have x86_64 in their universal compilation (because armv7, arm64, and i386 are the standards), so it breaks.

Is there a special reason it was swapped? Is there an easy way to swap it back to default to i386?

Thanks
Indigo

**Comment by c-parsons** [comment]
We indeed changed the default for this here recently as it more closely reflected the desired default for several users.
You can always change defaults for your builds by changing your ~/.bazelrc.

For instance, append this to the end of your ~/.bazelrc to build with i386 by default:

build --ios_cpu=i386
