### ISSUE TITLE
Bazel doesn't like directories containing '+'

### ISSUE THREAD

**Issue by kayasoze** [google/bazel#399]
❯❯❯ cd c++/samples                                                                                                                                                                                              
    ~/w/t/c/c/samples ❯❯❯ touch BUILD                                                                                                                                                                                                
    ~/w/t/c/c/samples ❯❯❯ bazel build ...
    ERROR: 'third-party/capnproto/c++/samples' is not a valid package name.

**Comment by kchodorow** [comment]
Tracking "allow (all) other characters" on #374.
