### ISSUE TITLE
-Wformat error

### ISSUE THREAD

**Issue by tfarina** [google/bazel#42]
$ ./compile.sh
...
third_party/ijar/classfile.cc: In function 'devtools_ijar::ClassFile* devtools_ijar::ReadClass(const void*, size_t)':
third_party/ijar/classfile.cc:1393:35: error: expected ')' before 'PRIx32'
third_party/ijar/classfile.cc:1393:60: warning: spurious trailing '%' in format [-Wformat]

**Comment by kchodorow** [comment]
What system are you on?  Can you paste the output of running:

    $ g++ -v

**Comment by tfarina** [comment]
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.7.3-2ubuntu1~12.04' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --with-system-zlib --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.7.3 (Ubuntu/Linaro 4.7.3-2ubuntu1~12.04)

**Comment by igkm** [comment]
You can explicitly request inclusion by using __STDC_FORMAT_MACRO, along with __STDC_LIMIT_MACROS

diff --git a/third_party/ijar/classfile.cc b/third_party/ijar/classfile.cc
index 90749ff..a170d8a 100644
--- a/third_party/ijar/classfile.cc
+++ b/third_party/ijar/classfile.cc
@@ -27,6 +27,7 @@
 // http://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4
 
 #define __STDC_LIMIT_MACROS 1
+#define __STDC_FORMAT_MACROS 1
 #include <inttypes.h> // for PRIx32
 #include <stddef.h>
 #include <stdio.h>

**Comment by tfarina** [comment]
Thanks! That works for me. Looking forward to see a fix (this or another) for this merged in the mainline tree.
