### ISSUE TITLE
archive.h  not  found

### ISSUE THREAD

**Issue by 0xmalloc** [google/bazel#43]
Creating JavaBuilder_deploy.jar...
Compiling client .cc files...
src/main/cpp/blaze.cc:66:10: fatal error: 'archive.h' file not found

**Comment by tfarina** [comment]
You have to install libarchive-dev as recommended by http://bazel.io/docs/install.html.

If you are on Ubuntu you can run the following command line:

 $ sudo apt-get install libarchive-dev

**Comment by 0xmalloc** [comment]
i use centos and i have installed  libarchive;
the new error message is below:
Package libarchive was not found in the pkg-config search path.
Perhaps you should add the directory containing `libarchive.pc'
to the PKG_CONFIG_PATH environment variable

**Comment by tfarina** [comment]
Looks like you haven't installed it yet.

**Comment by igkm** [comment]
I am on fedora, there is slight package renaming needed to get this going. 
libarchive-devel (instead of libarchive-dev) 
pkgconfig          (instead of pkg-config)
zlib-devel           (instead of zlib1g-dev - the fedora repo I point to has zlib-devel)

**Comment by damienmg** [comment]
Requalifying as a documentation issue

**Comment by hanwen** [comment]
https://github.com/google/bazel/commit/eb6e90397eff1083f0574b6cbd94eb9f42d2d239

**Comment by gioipv** [comment]
> You have to install libarchive-dev as recommended by http://bazel.io/docs/install.html.
> 
> If you are on Ubuntu you can run the following command line:
> 
> $ sudo apt-get install libarchive-dev

It worked for me. thankyou. I installed with root permission.
