### ISSUE TITLE
bazel test fails on OS X 10.10.2

### ISSUE THREAD

**Issue by jbeder** [google/bazel#46]
Using the following BUILD file:

    cc_library(
      name = "foo",
      srcs = ["foo.cpp"],
      hdrs = ["foo.h"],
    )

    cc_test(
      name = "foo_test",
      srcs = ["foo_test.cpp"],
      deps = [":foo"],
    )

where `foo.h` is:

    int foo(int x);

`foo.cpp` is:

    #include "foo.h"
    int foo(int x) {
        return x * x;
    }

and `foo_test.cpp` is:

    #include "foo.h"
    #include <iostream>

    int main() {
        std::cout << "Hello, World " << foo(3) << "\n";
        return 0;
    }

then `bazel test --test_output=streamed :foo_test` produces the output:

    WARNING: Streamed test output requested so all tests will be run locally, without sharding, one at a time.
    INFO: Found 1 test target...
    exec ${PAGER:-/usr/bin/less} "$0" || exit 1
    dyld: Library not loaded: bazel-out/local_darwin-fastbuild/bin/libfoo.so
      Referenced from: /private/var/tmp/_blaze_beder/28185150b94b8129abda95172b3b0fc5/workspace/bazel-out/local_darwin-fastbuild/bin/foo_test.runfiles/./foo_test
      Reason: image not found
    tools/test/test-setup.sh: line 16:  1519 Trace/BPT trap: 5       "$@"
    FAIL: //:foo_test (see /private/var/tmp/_blaze_beder/28185150b94b8129abda95172b3b0fc5/workspace/bazel-out/local_darwin-fastbuild/testlogs/foo_test/test.log).
    Target //:foo_test up-to-date:
      bazel-bin/foo_test
    INFO: Elapsed time: 0.190s, Critical Path: 0.11s
    //:foo_test                                                              FAILED

    Executed 1 out of 1 tests: 1 fails locally.

If I run `bazel build :foo_test`, then it builds correctly, and I can run `./bazel-bin/foo_test`, and it correctly produces the output `Hello, World 9`.

I'm running OS X Yosemite, 10.10.2 (14C1514), with `gcc --version`:

    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
    Target: x86_64-apple-darwin14.1.0
    Thread model: posix

`clang --version`:

    Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
    Target: x86_64-apple-darwin14.1.0
    Thread model: posix

I'm synced to bazel's master branch, change 03bad4619075aa77876698c55827aa54e7426ea9.

**Comment by Caffeinix** [comment]
I was able to reproduce this using the built-in cpp example with no modifications:

~~~
$ bazel test --test_output=all //examples/cpp:hello-success_test
INFO: Found 1 test target...
FAIL: //examples/cpp:hello-success_test (see /private/var/tmp/_blaze_phoenix/70ce3f379b09976e83961c12a3bbdb4e/test_cc_app/bazel-out/local_darwin-fastbuild/testlogs/examples/cpp/hello-success_test/test.log).
INFO: From Testing //examples/cpp:hello-success_test:
==================== Test output for //examples/cpp:hello-success_test:
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
dyld: Library not loaded: bazel-out/local_darwin-fastbuild/bin/examples/cpp/libhello-lib.so
  Referenced from: /private/var/tmp/_blaze_phoenix/70ce3f379b09976e83961c12a3bbdb4e/test_cc_app/bazel-out/local_darwin-fastbuild/bin/examples/cpp/hello-success_test.runfiles/examples/cpp/hello-success_test
  Reason: image not found
tools/test/test-setup.sh: line 16:  2309 Trace/BPT trap: 5       "$@"
================================================================================
Target //examples/cpp:hello-success_test up-to-date:
  bazel-bin/examples/cpp/hello-success_test
INFO: Elapsed time: 0.164s, Critical Path: 0.10s
//examples/cpp:hello-success_test                                        FAILED

Executed 1 out of 1 tests: 1 fails locally.
~~~

bazel run //examples/cpp:hello-world works fine, however, and it has the same library dependency (and is in fact the same source file).

I am also on OS X 10.10.2.

**Comment by damienmg** [comment]
Hello, thank you for reporting it. We were already aware of that problem and it is a bit tricky to solve. I will report when I finally find a solution.
