### ISSUE TITLE
Works on SUSE 12.3

### ISSUE THREAD

**Issue by kohlerm** [google/bazel#55]
I've got the example compiled on Suse 12.3 
I only had to install libarchive-devel:

zypper install libarchive-devel

**Comment by kchodorow** [comment]
Does this resolve https://github.com/google/bazel/issues/50 for you, as well?

**Comment by kohlerm** [comment]
No it does not solve this problem. OpenSuse 12.3 uses a new glibc

Kristina <notifications@github.com> schrieb am Mi., 25. März 2015 um
21:36 Uhr:

**Comment by damienmg** [comment]
Kristina can you update the readme on supported OS?

**Comment by ulfjack** [comment]
This might be fixed now. I think the new protoc is fully statically linked, which avoids the glibc issue.

**Comment by wxjttxs** [comment]
hello everyone, i want to know whether the Bazel could be installed on suse linux  or not, thank you.
