### ISSUE TITLE
Compiling the Java example with SAP JVM  does not work

### ISSUE THREAD

**Issue by kohlerm** [google/bazel#56]
Compiling with the java example with SAP JVM (a closed source fork of the  Oracle VM) does not work because the SAP JVM does not support the -client option. 
replacing the -client option with -server in
src/main/java/com/google/devtools/build/lib/rules/java/JavaConfigurationLoader.java
works around this problem. 
Probably -client should not be a baked in default option. 

The error message is misleading. It mentions that the --verbose option should be used but that does not seem to exist. 
There is also no hint that it fails because of -client option missing. E.g. I only saw when using strace.

**Comment by damienmg** [comment]
Recent JVM all have the -client option. bazel build -s or bazel build --verbose should have worked.

The workaround is not immediate and might take some time because java launch with -server option for ridically low memory space (in today criteria).

**Comment by kohlerm** [comment]
SAP JVM is a pure server VM and -client was therefore removed. 
This is not a very urgent request yet, but if there would be some way to override the -client option, that would be helpful. 

--verbose does not work for me:

~/bazel>$HOME/bazel/output/bazel   build  --verbose  //examples/java-native/src/main/java/com/example/myproject:hello-world 
Unrecognized option: --verbose

**Comment by damienmg** [comment]
Sorry the option is --verbose_failures

What is the actual error message without the --verbose_failures?

**Comment by kohlerm** [comment]
I tried that one already, but I think there was no difference have to try it again. 
Note that the error message also says that one should use --verbose
...

**Comment by kchodorow** [comment]
Can you paste the entire command you're running + bazel output?

**Comment by hanwen** [comment]
side note: we need to document what information people should supply on bugreports.

**Comment by kohlerm** [comment]
Sorry I was in a hurry.
Upon further inspection it prints that -client is not recognized, but I don't think it is obvious what it means. 


~/bazel>$HOME/bazel/output/bazel   build    //examples/java-native/src/main/java/com/example/myproject:hello-world 
INFO: Found 1 target...
INFO: From Building examples/java-native/src/main/java/com/example/myproject/hello-world.jar (0 files):
Unrecognized option: -client
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
ERROR: /root/bazel/examples/java-native/src/main/java/com/example/myproject/BUILD:3:1: Java compilation in rule '//examples/java-native/src/main/java/com/example/myproject:hello-world' failed: java failed: error executing command external/local-jdk/bin/java -Xbootclasspath/p:external/local-jdk/lib/tools.jar -client -jar tools/jdk/JavaBuilder_deploy.jar ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //examples/java-native/src/main/java/com/example/myproject:hello-world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.488s, Critical Path: 0.04s


 I was also confused that it says:
external/local-jdk/bin/java

**Comment by kchodorow** [comment]
Thanks!  

--verbose_failures will give you the actual command line that caused the error, which you probably don't care about in this case (we know it's the -client flag).

external/local-jdk is the autogenerated path Bazel uses as a symlink to the local JDK.

I don't know enough about JVMs to be able to answer what we should do about -client, @damienmg?

**Comment by damienmg** [comment]
We should basically be able to provide a list of host flags to the jvm so one can deactivate the -client. I will work on that along with the full support of the java_toolchain. For now I think I can submit a workaround. Let me look at that.

**Comment by damienmg** [comment]
Ok I have look around and the workaround is not feasible. Fixing that need a refactoring.
