### ISSUE TITLE
Permission denied when running 'bazel build'

### ISSUE THREAD

**Issue by rbvermaa** [google/bazel#58]
When going through the example in the documentation, I am getting the following error while running `bazel build`:

    $ bazel build my-project:my-runner --verbose_failuresExtracting Bazel installation...
    ......
    INFO: Found 1 target...
    ERROR: /home/rbvermaa/src/bazel/base_workspace/my-project/BUILD:1:1: Creating runfiles tree bazel-out/local_linux-fastbuild/bin/my-project/my-runner.runfiles failed: build-runfiles failed: error executing command 
      (cd /home/rbvermaa/.cache/bazel/_blaze_rbvermaa/ce51c282b5b9dadfc520c685445c68ce/base_workspace && \
      exec env - \
      /home/rbvermaa/.cache/bazel/_blaze_rbvermaa/ce51c282b5b9dadfc520c685445c68ce/base_workspace/_bin/build-runfiles bazel-out/local_linux-fastbuild/bin/my-project/my-runner.runfiles_manifest bazel-out/local_linux-fastbuild/bin/my-project/my-runner.runfiles): com.google.devtools.build.lib.shell.ExecFailedException: java.io.IOException: Cannot run program "/home/rbvermaa/.cache/bazel/_blaze_rbvermaa/ce51c282b5b9dadfc520c685445c68ce/base_workspace/_bin/process-wrapper" (in directory "/home/rbvermaa/.cache/bazel/_blaze_rbvermaa/ce51c282b5b9dadfc520c685445c68ce/base_workspace"): error=13, Permission denied: build-runfiles failed: error executing command 
      (cd /home/rbvermaa/.cache/bazel/_blaze_rbvermaa/ce51c282b5b9dadfc520c685445c68ce/base_workspace && \
      exec env - \
      /home/rbvermaa/.cache/bazel/_blaze_rbvermaa/ce51c282b5b9dadfc520c685445c68ce/base_workspace/_bin/build-runfiles bazel-out/local_linux-fastbuild/bin/my-project/my-runner.runfiles_manifest bazel-out/local_linux-fastbuild/bin/my-project/my-runner.runfiles): com.google.devtools.build.lib.shell.ExecFailedException: java.io.IOException: Cannot run program "/home/rbvermaa/.cache/bazel/_blaze_rbvermaa/ce51c282b5b9dadfc520c685445c68ce/base_workspace/_bin/process-wrapper" (in directory "/home/rbvermaa/.cache/bazel/_blaze_rbvermaa/ce51c282b5b9dadfc520c685445c68ce/base_workspace"): error=13, Permission denied.
    Target //my-project:my-runner failed to build
    INFO: Elapsed time: 1.994s, Critical Path: 0.51s

Looking at the files that bazel is failing on, they seem to lack the executable flag, while in the installation prefix of bazel, they are actually executable.    
    
    $ ll /home/rbvermaa/.cache/bazel/_blaze_rbvermaa/install/c319309e20c3f37a277f6e599681275a/_embedded_binaries/
    total 13488
    -rw-r--r-- 1 rbvermaa users      109 Mar 22  2025 build_interface_so
    -rw-r--r-- 1 rbvermaa users    64181 Mar 22  2025 build-runfiles
    -rw-r--r-- 1 rbvermaa users        0 Mar 22  2025 client_info
    -rw-r--r-- 1 rbvermaa users       33 Mar 22  2025 install_base_key
    -rw-r--r-- 1 rbvermaa users        4 Mar 22  2025 java.version
    -rw-r--r-- 1 rbvermaa users      801 Mar 22  2025 jdk.BUILD
    -rw-r--r-- 1 rbvermaa users      820 Mar 22  2025 jdk.WORKSPACE
    -rw-r--r-- 1 rbvermaa users 13589089 Mar 22  2025 libblaze.jar
    -rw-r--r-- 1 rbvermaa users    94557 Mar 22  2025 libunix.so
    -rw-r--r-- 1 rbvermaa users    19486 Mar 22  2025 namespace-sandbox
    -rw-r--r-- 1 rbvermaa users    14008 Mar 22  2025 process-wrapper
    
The bazel installation directory looks like:
    
    $ ls -l /nix/store/wl19f5z591zrmrp66mbdjr1zi5z5kdr6-bazel-20150325.9a0dc1b2/share/bazel/
    total 37712
    dr-xr-xr-x 3 root nixbld     4096 Jan  1  1970 actoolzip
    -r-xr-xr-x 1 root nixbld 12367529 Jan  1  1970 bazel
    -r-xr-xr-x 1 root nixbld      167 Jan  1  1970 build_interface_so
    dr-xr-xr-x 3 root nixbld     4096 Jan  1  1970 buildjar
    -r-xr-xr-x 1 root nixbld    64181 Jan  1  1970 build-runfiles
    dr-xr-xr-x 3 root nixbld     4096 Jan  1  1970 bundlemerge
    dr-xr-xr-x 8 root nixbld     4096 Jan  1  1970 classes
    -r-xr-xr-x 1 root nixbld   307789 Jan  1  1970 client
    -r-xr-xr-x 1 root nixbld        0 Jan  1  1970 client_info
    dr-xr-xr-x 3 root nixbld     4096 Jan  1  1970 ibtoolzip
    dr-xr-xr-x 2 root nixbld     4096 Jan  1  1970 ijar
    -r--r--r-- 1 root nixbld       33 Jan  1  1970 install_base_key
    -r--r--r-- 1 root nixbld        4 Jan  1  1970 java.version
    -r--r--r-- 1 root nixbld      801 Jan  1  1970 jdk.BUILD
    -r--r--r-- 1 root nixbld      820 Jan  1  1970 jdk.WORKSPACE
    -r--r--r-- 1 root nixbld 13589089 Jan  1  1970 libblaze.jar
    -r-xr-xr-x 1 root nixbld    94557 Jan  1  1970 libunix.so
    -r--r--r-- 1 root nixbld       58 Jan  1  1970 MANIFEST.MF
    dr-xr-xr-x 3 root nixbld     4096 Jan  1  1970 momczip
    -r-xr-xr-x 1 root nixbld    19486 Jan  1  1970 namespace-sandbox
    dr-xr-xr-x 2 root nixbld     4096 Jan  1  1970 native
    dr-xr-xr-x 2 root nixbld     4096 Jan  1  1970 objs
    -r--r--r-- 1 root nixbld 12059740 Jan  1  1970 package.zip
    dr-xr-xr-x 3 root nixbld     4096 Jan  1  1970 plmerge
    -r-xr-xr-x 1 root nixbld    14008 Jan  1  1970 process-wrapper
    dr-xr-xr-x 3 root nixbld     4096 Jan  1  1970 singlejar
    dr-xr-xr-x 3 root nixbld     4096 Jan  1  1970 src
    dr-xr-xr-x 2 root nixbld     4096 Jan  1  1970 test_classes
    dr-xr-xr-x 3 root nixbld     4096 Jan  1  1970 xcodegen
    
    
One thing that might be different in my setup is the fact that the installation of bazel is readonly, perhaps that is related?

**Comment by rbvermaa** [comment]
Actually, I have tested if the issue is there with a writable installation prefix, and that gives the same error.

**Comment by kchodorow** [comment]
What kind of system is this running on?  Can you paste the output of `unzip -l $(which bazel)`?

**Comment by rbvermaa** [comment]
This is on NixOS, which is a Linux distribution.

    $ unzip -l /nix/store/wl19f5z591zrmrp66mbdjr1zi5z5kdr6-bazel-20150325.9a0dc1b2/share/bazel/bazel
    Archive:  /nix/store/wl19f5z591zrmrp66mbdjr1zi5z5kdr6-bazel-20150325.9a0dc1b2/share/bazel/bazel
      Length      Date    Time    Name
    ---------  ---------- -----   ----
     13589089  01-01-1980 00:00   libblaze.jar
        94557  01-01-1980 00:00   libunix.so
        64181  01-01-1980 00:00   build-runfiles
        14008  01-01-1980 00:00   process-wrapper
            0  01-01-1980 00:00   client_info
          109  01-01-1980 00:00   build_interface_so
          820  01-01-1980 00:00   jdk.WORKSPACE
          801  01-01-1980 00:00   jdk.BUILD
        19486  01-01-1980 00:00   namespace-sandbox
           33  01-01-1980 00:00   install_base_key
            4  01-01-1980 00:00   java.version
    ---------                     -------
     13783088                     11 files

**Comment by damienmg** [comment]
process-wrapper hasn't the x flag in the output directory.

**Comment by damienmg** [comment]
What you call the installation directory is actually just the build output of the compile.sh script. In the real installation directory the x flag is missing. Now the question is why

**Comment by rbvermaa** [comment]
Indeed, we copied the results that were in output/ after compile.sh was run. What do you mean exactly by 'real installation directory'? 

I tried looking through the code and saw some chmod calls in the Java code, however, when running strace I don't see any chmod on any of the files in $HOME/.cache/bazel/_blaze_rbvermaa/install/c319309e20c3f37a277f6e599681275a/_embedded_binaries/  come by.

**Comment by damienmg** [comment]
There is no installation directory per se. Bazel is a self-extractable zip, we call install base the folder that contains the _embedded_binaries one. 

You cannot strace Bazel, it is launching a server in the background.

The files in /home/rbvermaa/.cache/bazel/_blaze_rbvermaa/ce51c282b5b9dadfc520c685445c68ce/base_workspace/_bin/ should be symbolic links. I think we should just do chmod when unzipping files. Depending on the zip configuration it will change.

**Comment by damienmg** [comment]
Ok after took a look at the code, it depends on the version of libarchive. I will send a workaround tomorrow to enforce the executable flags on extracted files.

**Comment by damienmg** [comment]
I just thought that it would be easier for you to test, the envision solution is to replace the line 229 of src/main/cpp/blaze.cc:
794c794
<     int fd = open(path.c_str(), O_CREAT | O_WRONLY, archive_entry_perm(entry));
---
>     int fd = open(path.c_str(), O_CREAT | O_WRONLY, 0755);

Can you try to do that change and see if that fixes your issue?

**Comment by rbvermaa** [comment]
@damienmg Thanks for the quick response, the patch seems to work!

**Comment by damienmg** [comment]
The patch is going through the review process and should be here in a day

**Comment by rbvermaa** [comment]
Great, thanks!
