### ISSUE TITLE
new_local_repository does not respect 'includes' attribute

### ISSUE THREAD

**Issue by pmbethe09** [google/bazel#66]
suppose you want to link against the system jni headers on a Mac that might be a WORKSPACE entry of:

```
new_local_repository(
    name = "jni-local",
    build_file = "BUILD.extjni",
    path = "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/include",
)
bind(
    name = "jni",
    actual = "@jni-local//:headers",
)
---
BUILD.extjni of:

genrule(
    name = "empty",
    outs = ["empty.cc"],
    cmd = "echo -n 'void external_jdk_empty(){}' > $@",
)
cc_library(
    name = "headers",
    srcs = [":empty"],
    hdrs = glob(["**/*.h"]),
    includes = [
        ".",
        "darwin",
    ],
    visibility = ["//visibility:public"],
)
```

When you try and compile a file which has `#include <jni.h>`:

```
ERROR: jni/BUILD:10:1: undeclared inclusion(s) in rule '//jni:libreverse.so':
this rule is missing dependency declarations for the following files included by 'jni/Reverse.cpp':
  '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/include/jni.h'
  '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/include/darwin/jni_md.h'.
```

**Comment by pmbethe09** [comment]
that was supposed to be include jni.h with angle brackets.

**Comment by pmbethe09** [comment]
Not sure I agree using the example above: bazel build //external:jni

ERROR: /private/var/tmp/_bazel_pbethe/d03eb8f816153c36c4229eeab3f690b4/.external-repository/jni-local/BUILD:12:12: error globbing [**/*.h]: /private/var/tmp/_bazel_pbethe/d03eb8f816153c36c4229eeab3f690b4/.external-repository/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/external/jni-local/darwin (Too many levels of symbolic links).
ERROR: /Users/pbethe/School/Bridge/WORKSPACE:7:1: Target '@jni-local//:headers' contains an error and its package is in error and referenced by '//external:jni'.

**Comment by kchodorow** [comment]
I think this can be worked around with more judicious globbing until https://github.com/google/bazel/issues/87 is fixed.
