### ISSUE TITLE
Bazel lacks support for proprietary (closed source) C++ libraries.

### ISSUE THREAD

**Issue by gearoid-murphy** [google/bazel#70]
Bazel currently supports this in Java via the java_import rule but C++ appears to be lacking this kind of feature [1]. Please consider extending the default Bazel build rules to allow C++ builds to integrate third party libraries that consist of header files and precompiled library binaries.

1. http://bazel.io/docs/build-encyclopedia.html

**Comment by pmbethe09** [comment]
cc_library allows srcs to contain precompiled ".a" and ".so" files.

Note: on Mac you will need an "empty.cc" in srcs as clang/bazel do not handle empty srcs (as in nothing to actually compile)

**Comment by laszlocsomor** [comment]
Sounds like it's WAI. Closing.

**Comment by ulfjack** [comment]
I'd prefer to disallow adding precompiled files to srcs and instead add a cc_import rule. We have seen some problems with this internally, and it also makes the code a bit more complex than we'd like.

**Comment by gearoid-murphy** [comment]
+1 cc_import rule. This would bring the semantics inline with the existing java convention. FWIW, it would also be nice to allow absolute file paths to reference system libraries that exist outside of the workspace.

**Comment by pmbethe09** [comment]
An absolute-path import can be done by using 'new_local_repository' in your WORKSPACE file and then binding it.  Although it does not yet work correctly in the case of imports.  (https://github.com/google/bazel/issues/66)
