### ISSUE TITLE
Add GitHub Linguist config for BUILD/Skylark

### ISSUE THREAD

**Issue by davidzchen** [google/bazel#72]
We should add an entry to [github/linguist](https://github.com/github/linguist) for BUILD/Skylark so that GitHub can 1) add proper syntax highlighting for displaying BUILD and .bzl files and 2) include them in the language stats for repositories.

It might also be good to add an entry for ASCII protos/CROSSTOOL as well. There is a Linguist entry for Protocol Buffer message definitions but not for ASCII protos.

**Comment by hanwen** [comment]
Anyone know ruby out there that'd be interested?

**Comment by hanwen** [comment]
Since both .bzl and BUILD are syntactically correct python, linguist could be configured to use that?

**Comment by damienmg** [comment]
I have some experience in ruby but I think it is just simpler to use the
Python highlighting
Le jeu. 2 avr. 2015 à 07:38, Han-Wen Nienhuys <notifications@github.com> a
écrit :

**Comment by hanwen** [comment]
we can fix this on our side by introducing .gitattributes with 

 *.bzl lang=python

**Comment by hanwen** [comment]
see https://github.com/github/linguist/pull/2348 

It was rejected because there aren't enough .bzl files in github yet.

**Comment by davidzchen** [comment]
I see. I was not aware of this requirement.

Let's try again once there is more Skylark code checked in.

**Comment by davidzchen** [comment]
FYI github/linguist#2846 was just merged to add the .bzl file extension to Linguist to recognize Skylark files as Python.
