### ISSUE TITLE
Install rules and targets similar to `make install`

### ISSUE THREAD

**Issue by davidzchen** [google/bazel#73]
Build systems such as Autotools and CMake have a mechanism to generate an install target that can be configured via install hooks or rules. It would be good to have a similar mechanism in Bazel.

**Comment by davidzchen** [comment]
While it is possible to implement this with `genrule`, it may be better to have some abstractions on top of `install`. It might also be better to have a separate command since `bazel install //package:target` is more intuitive than `bazel build //package:install_target` and since there should be a flag similar to `--prefix` for setting the install prefix.

**Comment by laszlocsomor** [comment]
Oh wait, I misunderstood. Can you be more specific of what this would do?

**Comment by davidzchen** [comment]
Most Makefile-based projects, including Autotools and CMake-based projects, generate a `make install` target that installs binaries to `$PREFIX/bin`, libraries to `$PREFIX/lib`, configs and man pages to `$PREFIX/share`, etc. Having a similar mechanism in Bazel would simplify the migration path from Autotools and CMake to Bazel.

**Comment by hanwen** [comment]
I think this can be better done outisde of bazel for the moment, by having a script that collects different targets and sticks them in a tarball or installs on the filesystem. Also, installs should be able to run as root (for installing files into /usr/ etc.), but that can't work with the client/server model of bazel.

We also lack the surrounding infrastructure btw, so I think this is premature:

* there are no rules for generating man pages
* bazel doesn't know what are config files, and what are binaries. Typically, we open files in the runfiles tree.
* we can't smoothly link to host libraries
* philosophically: we try to build self-contained artifacts (eg. statically linked binaries), while systems that are strewn over the filesystem typically hook up to other parts of the Unix installation.

Rather than trying to invent a feature for bazel, can we first try to build something as an external script/add-on, see what the problems are, and then see what features bazel needs?

**Comment by davidzchen** [comment]
> there are no rules for generating man pages

I think this could easily be solved by adding those build rules. For users who write man pages in a format such as POD, it should be easy to add a macro wrapping a genrule that runs something like `pod2man`.

> we can't smoothly link to host libraries

As I understand, the currently solution is using `linkopts` etc., which is not ideal. We have had some discussion regarding this while [discussing the autoconfiguration mechanism](https://groups.google.com/forum/#!topic/bazel-discuss/u5MupIvd768). What is the plan for this?

> Rather than trying to invent a feature for bazel, can we first try to build something as an external script/add-on, see what the problems are, and then see what features bazel needs?

SGTM.

Can we keep this issue open for continuing this discussion and for exploring this? I can change the title appropriately.

**Comment by hanwen** [comment]
On Wed, Apr 15, 2015 at 2:54 PM, David Z. Chen <notifications@github.com>
wrote:

> there are no rules for generating man pages
>
> I think this could easily be solved by adding those build rules. For users
> who write man pages in a format such as POD, it should be easy to add a
> macro wrapping a genrule that runs something like pod2man.
>
> we can't smoothly link to host libraries
>
> As I understand, the currently solution is using linkopts etc., which is
> not ideal. We have had some discussion regarding this while discussing
> the autoconfiguration mechanism
> <https://groups.google.com/forum/#!topic/bazel-discuss/u5MupIvd768>. What
> is the plan for this?
>

Damien is experimenting to see how far he can come with autogenerating
BUILD files using a script; from there we can see what if and how we could
integrate this with Bazel.


> Rather than trying to invent a feature for bazel, can we first try to
> build something as an external script/add-on, see what the problems are,
> and then see what features bazel needs?
>
> SGTM.
>
> Can we keep this issue open for continuing this discussion and for
> exploring this? I can change the title appropriately.
>

Sure. When you do, please describe what problem you want to solve, rather
than what feature you'd like to see.


-- 
Han-Wen Nienhuys
Google Munich
hanwen@google.com

**Comment by davidzchen** [comment]
Sounds good. Thanks for the update, Han-Wen.

**Comment by dfwesdfqw** [comment]
Hey, why is this issue closed? How should an install be done?

**Comment by ZhenshengLee** [comment]
@OznOg FYI For now, there are custom bazel extensions for install target. like https://github.com/RobotLocomotion/drake/blob/master/tools/install/README.md or https://github.com/ApolloAuto/apollo/tree/master/tools/install 

It seems that install target solution is not recommened by bazel officially? am I right? @hanwen
