### ISSUE TITLE
Add instructions how to install bazel tools

### ISSUE THREAD

**Issue by filmil** [google/bazel#77]
The page http://bazel.io/docs/install.html, named Installing actually only talks about compiling bazel.

There is nothing in terms of instructions how to take the binaries you got and make them universally available and useful :) on your system.  Yes, it is trivial to manipulate $PATH, but a few sentences on what bazel authors *recommend* be done would go a long way.

**Comment by laszlocsomor** [comment]
Updated; see effects soon (upon next doc push, ETA within 1-2 days).
