### ISSUE TITLE
Stickers in telegram

### ISSUE THREAD

**Issue by Nekbakht** [google/bazel#78]
what  Is name of Java file for stickers ?

**Comment by kchodorow** [comment]
I have no idea what you're talking about, can you clarify?

**Comment by Nekbakht** [comment]
How stickers working on telegram?
And how create new button for stickers?

**Comment by damienmg** [comment]
I think you are asking the question in the wrong place, this is the Bazel issue tracker. There is no part called telegram and no such thing called "stickers" anywhere in Bazel (nor any button since it is a command line software).

**Comment by damienmg** [comment]
https://github.com/DrKLO/Telegram/issues <-- Here the issue tracker for Telegram :)
