### ISSUE TITLE
Incorrect PATH in "Running Bazel"

### ISSUE THREAD

**Issue by cjdrake** [google/bazel#86]
On `bazel.io/docs/install.html` it says to modify your .bashrc file with this:

```bash
$ export PATH="$PATH:$HOME/bazel/output/bazel"
```

I think it should be `$HOME/bazel/output`, the directory of the `bazel` executable.

**Comment by laszlocsomor** [comment]
Correct, thanks for letting us know!
A change to fix it is already pending.



--
László Csomor | Software Engineer | laszlocsomor@google.com

Google Germany GmbH | Maximilianstrasse 11-15 | 80539 München | Germany
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschäftsführer: Graham Law, Christine Elizabeth Flores

2015-03-31 7:29 GMT+02:00 Chris Drake <notifications@github.com>:
