### ISSUE TITLE
Including headers from other packages

### ISSUE THREAD

**Issue by brynmathias** [google/bazel#92]
Hi,

This might have been answered before but I haven't found a solution in either the docs, any open pull requests or my playing around.

I wish to include files in my build form a different package.
however I can't do:
`includes = ["include", "../otherpackage/include"]` so am wondering how to do this within Bazel's methodology.

I have a package core with a libarary in it.

    package(default_visibility = ["//visibility:public"])

    cc_library(
        name = "Mylib",
        srcs = ["Mylib.c",],
        hdrs = ["Mylib.h",],
        includes = ["include", "headers"],
        deps = ["//project/dependancy:headers",],
    )
    

in the dependancy package I have:

    package(default_visibility = ["//visibility:public"])

    filegroup(
        name = "headers",
        srcs = glob([
            "*.h",
        ]),
    )

This doesn't work, so I'm getting something wrong.
I have tried including the headers as `data = ["//project....",]`
but that doesn't help, its quite likley that I'm just making a hash of things but if anyone has some quick pointers, or can add an example of such to the documentaion I'd be very appreciative.

**Comment by pmbethe09** [comment]
The Google way to do this is includes rooted at the WORKSPACE level.

So MyLib can just depend on a cc_library in //project/dependancy:whatever 
and then in MyLib .cc files use
#include "project/dependency/some_header.h"
As all bazel compilations have an implicit -I on the directory containing WORKSPACE.

However, if you can't do that yet, then the 'includes' attribute can be used.
But, not in the way you might think.  Includes is for how THIS library is depended on by others (not what this library depends on).
So.  In //package/dependency
cc_library(
    name = "whatever",
    srcs = ["whatever.c"],
    hdrs = glob(["*.h"]),
    includes = ["."],
)

The magic is: includes = ["."]
Now when MyLib depends on //project/dependency:whatever it will be able to reference the headers in there without extra work.

**Comment by damienmg** [comment]
Closing the issue, feel free to reopen it if you have further questions.
