### ISSUE TITLE
Using External Dependencies

### ISSUE THREAD

**Issue by aarossig** [google/bazel#95]
I am interested in using other projects in my source tree such as googletest:

https://github.com/chronos-tachyon/googletest-bazel

This project has written BUILD rules for googletest. One thing that I am not a fan of is that gtest would be located in my WORKSPACE root. This could become a namespacing issue where collisions might occur. I don't have control over the locations of these targets.

Is there a general way to move targets without updating the include paths? It would be nice to place gtest in something like //third_party/gtest without updating the includes.

Any thoughts?

**Comment by davidzchen** [comment]
You can use the `includes` attribute of `cc_library` to set the include path so that you don't need to change the include paths in the source files: http://bazel.io/docs/build-encyclopedia.html#cc_library

**Comment by damienmg** [comment]
You can use the external_repository mechanism which is suited exactly for this use-case.

See http://bazel.io/docs/build-encyclopedia.html#bind
and http://bazel.io/docs/build-encyclopedia.html#local_repository

We have plan to support remote repository pull directly git repository but it is still unfinished work.

Assigning to Kristina if you have further question.

**Comment by kchodorow** [comment]
Closing, feel free to reopen if you want to ask anything.
